"""Phase 255D — the closeout contract.

**What this asserts.** The ARTEFACTS a close-out is defined to produce, for a
phase. Not that closeout *ran* — that is unfalsifiable from inside a
repository, and a check that cannot fail is the defect this phase exists to
stop shipping.

**Why the fixtures are hand-written.** Decision 5, sharpened by 255C into
*independent reference*: a positive control must be satisfied by something
that does not reimplement the procedure. `fixtures/bad/` is a complete
miniature repository with one planted defect per assertion, written by hand
and committed. A fixture generated by the code under test would prove only
that the code agrees with itself — which is exactly how 255C shipped a guard
that could not fail.

**The check's own first bug is recorded here** because it is the reason this
file exists: the first cut of A4 used one `re.findall` with `re.S`, so a
non-greedy `.*?` ran across a newline and matched a later heading's number
from an earlier heading's line. It reported `#5` twice against a log whose
headings were a clean `#1..#7`. **The check was wrong, not the log** — the
same DOTALL-across-a-line-boundary defect that ate a guard in Phase 255B.
Caught by running the check against a real closed phase before trusting it.
"""
from __future__ import annotations

import json
import pathlib
import subprocess
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILL = ROOT / ".claude" / "skills" / "closeout"
sys.path.insert(0, str(SKILL))

from closeout_check import ASSERTION_IDS, check  # noqa: E402

BAD = SKILL / "fixtures" / "bad"
GOOD = SKILL / "fixtures" / "good"

#: The real phase this check is pinned against. 255C is the first phase
#: closed under it, and D6 requires the script to pass on a phase it was not
#: written for. Running only against fixtures would test the fixtures.
PINNED_REAL_PHASE = "255C"


class TestTheKnownBadFixtureFailsEveryAssertion:
    """A guard that cannot fail is not a guard."""

    @pytest.fixture(scope="class")
    def fails(self):
        return check(BAD, "ZZZ")

    @pytest.mark.parametrize("aid", ASSERTION_IDS)
    def test_this_assertion_fires(self, fails, aid):
        assert any(f.startswith(aid) for f in fails), (
            f"{aid} did not fire on the known-bad fixture, which plants one "
            f"defect per assertion. Either the planted defect was removed or "
            f"{aid} cannot fail. Failures seen: {fails}")

    def test_the_fixture_is_not_silently_empty(self, fails):
        assert len(fails) >= len(ASSERTION_IDS), (
            f"expected at least {len(ASSERTION_IDS)} failures, got {len(fails)}")


class TestA4RequiresTheCommitToResolve:
    """A Commit line must name a commit that exists.

    The first cut of A4 checked only that the words `**Commit.**` were
    present, so `This one.` passed — 255D bug fixes #5 and #6 shipped that
    way, and 255C #7 said "See the close-out commit". A check that passes on
    a non-answer cannot fail on the thing it exists for.
    """

    @pytest.fixture(scope="class")
    def a4(self):
        return [f for f in check(BAD, "ZZZ") if f.startswith("A4")]

    def test_a_non_hash_commit_line_fails(self, a4):
        assert any("name no" in f and "#1 'This one.'" in f for f in a4), a4

    def test_a_hash_that_is_not_a_commit_fails(self, a4):
        assert any("do not resolve" in f and "#4 aaaaaaa" in f for f in a4), a4

    def test_a_real_hash_resolves(self):
        from closeout_check import unresolved_commits
        assert unresolved_commits(ROOT, " `f279533`.") == []

    def test_a_sibling_repository_is_resolved_there(self):
        """`hash` (name) resolves in the sibling checkout `name`.

        Positive control: this repository named as its own sibling, so the
        test does not depend on any other checkout being present.
        """
        from closeout_check import unresolved_commits
        assert unresolved_commits(ROOT, f" `f279533` ({ROOT.name}).") == []

    def test_an_absent_sibling_is_reported_not_skipped(self):
        from closeout_check import unresolved_commits
        assert unresolved_commits(
            ROOT, " `f279533` (no-such-repo-255D).") == [
                "f279533 (no-such-repo-255D)"]


class TestTheKnownGoodFixturePasses:
    def test_no_assertion_fires(self):
        fails = check(GOOD, "ZZZ")
        assert fails == [], (
            "the corrected fixture must pass; a check that fails on correct "
            f"input is as useless as one that passes on bad: {fails}")


class TestAgainstTheRealRepository:
    def test_a_closed_phase_passes(self):
        """D6: run it against a phase it was not written for."""
        fails = check(ROOT, PINNED_REAL_PHASE)
        assert fails == [], (
            f"phase {PINNED_REAL_PHASE} is closed and must satisfy the "
            f"closeout contract: {fails}")

    def test_an_unknown_phase_does_not_pass_vacuously(self):
        """A phase with no documents at all must fail, not quietly succeed."""
        fails = check(ROOT, "999Q")
        assert fails, "a nonexistent phase passed the closeout check"


class TestThePushGuardNeverBlocksANonPushCommand:
    """v1.1-3. The lockout is the failure mode of this whole design.

    A guard on `Bash` that is wrong about WHICH commands it guards takes away
    the tool needed to remove it. This happened in D1: a guard meant for
    `git push` blocked a `cat`, because `PreToolUse` ignores the hook's `if`
    field in this build. Recovery was via the Write tool, which does not pass
    through a `Bash` matcher.
    """

    GUARD = SKILL / "pre_push_guard.sh"

    def _run(self, command: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            [str(self.GUARD)], input=json.dumps({
                "hook_event_name": "PreToolUse", "tool_name": "Bash",
                "tool_input": {"command": command}}),
            capture_output=True, text=True, timeout=120)

    @pytest.mark.parametrize("command", [
        "ls -la",
        "git status",
        "git log --oneline -3",
        'echo "git push"',                       # the words, inside a quote
        'grep -rn "git push" docs/',             # the words, as a search term
        "cat > /tmp/x <<'EOF'",
        "git pushx --not-a-real-subcommand",
    ])
    def test_a_non_push_command_is_let_through(self, command):
        r = self._run(command)
        assert r.returncode == 0, (
            f"the guard blocked a non-push command, which is the lockout "
            f"bug: {command!r} -> exit {r.returncode}\n{r.stderr}")

    def test_malformed_input_is_let_through(self):
        r = subprocess.run([str(self.GUARD)], input="not json",
                           capture_output=True, text=True, timeout=120)
        assert r.returncode == 0, (
            "the guard must stay out of the way when it cannot read its "
            "input; it must never be able to fail closed")

    @pytest.mark.parametrize("command", [
        "git push origin phase-255D-procedures-as-folders",
        "git push -u origin some-feature-branch",
    ])
    def test_a_phase_branch_push_is_let_through(self, command):
        """Close-out is what must happen before work reaches `master`.

        A phase branch is pushed many times while the phase is still open;
        that is normal, not a skipped close-out. A guard that blocked every
        push would block every work-in-progress push for the whole phase,
        and the only way to work would be to turn the guard off — which is
        worse than not having one.
        """
        r = self._run(command)
        assert r.returncode == 0, (
            f"the guard blocked a phase-branch push: {command!r}\n{r.stderr}")

    def test_master_is_recognised_as_guarded(self):
        from _pre_push_guard import targets_master
        assert targets_master("git push origin master", ROOT)
        assert targets_master("git push origin HEAD:master", ROOT)
        assert not targets_master("git push origin my-branch", ROOT)

    def test_a_real_push_is_recognised(self):
        """The other direction: the guard must actually engage on a push.

        It exits 0 here only if the repository's current phase is closed, so
        this asserts recognition rather than blocking — `is_git_push` is
        unit-tested for the classification itself.
        """
        from _pre_push_guard import is_git_push
        assert is_git_push("git push origin master")
        assert is_git_push("cd /x && git push -u origin branch")
        assert not is_git_push('echo "git push"')
