"""Phase 257 — the two no-model steps: census and entry_check.

**census** is a rule over the whole junction, never a search or a sample —
the reason the figures of record (F139) differ from the loose ones.

**entry_check** checks each finding against the DOCUMENT, not against the
model's account of it. Its known-bad fixture plants one defect per
rejection class and every class must fire; the known-good fixture must
pass. Both are hand-written (255D decision 5): a fixture generated by the
code under test proves only that it agrees with itself.
"""
from __future__ import annotations

import json
import pathlib
import sqlite3
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILL = ROOT / ".claude" / "skills" / "source-transmission"
sys.path.insert(0, str(SKILL))

from census import census  # noqa: E402
from entry_check import REJECTION_IDS, check  # noqa: E402

FIX = SKILL / "fixtures"


class TestEntryCheckKnownBad:
    @pytest.fixture(scope="class")
    def fails(self):
        return check(json.loads((FIX / "bad.json").read_text(encoding="utf-8")), FIX)

    @pytest.mark.parametrize("rid", REJECTION_IDS)
    def test_this_rejection_fires(self, fails, rid):
        assert any(f.startswith(rid + " ") for f in fails), (
            f"{rid} did not fire on the known-bad fixture: {fails}")

    def test_an_altered_quote_is_caught_by_the_document(self, fails):
        """E3: 6-speed quoted, 5-speed printed. Only reading the document tells."""
        assert any(f.startswith("E3") and "does not contain the quote" in f for f in fails)


class TestEntryCheckKnownGood:
    def test_the_good_fixture_passes(self):
        fails = check(json.loads((FIX / "good.json").read_text(encoding="utf-8")), FIX)
        assert fails == [], fails


def _db(tmp_path, pairs):
    db = tmp_path / "j.db"
    c = sqlite3.connect(db)
    c.execute("CREATE TABLE known_issue_models (issue_id INTEGER, make TEXT, model TEXT)")
    c.executemany("INSERT INTO known_issue_models VALUES (?,?,?)", pairs)
    c.commit(); c.close()
    return db


class TestCensus:
    def test_only_unknown_pairs_are_counted_with_their_rows(self, tmp_path):
        db = _db(tmp_path, [
            (1, "Honda", "PCX 150"), (2, "Honda", "PCX 150"),      # model-sourced: out
            (3, "Honda", "Africa Twin"),                           # ambiguous: out
            (4, "Honda", "CBR1000RR"), (5, "Honda", "CBR1000RR"),  # unknown, 2 rows
            (6, "Ducati", "Panigale V4"),                          # unknown, 1 row
        ])
        assert census(db) == {"Honda": [{"model": "CBR1000RR", "rows": 2}],
                              "Ducati": [{"model": "Panigale V4", "rows": 1}]}

    def test_the_make_filter(self, tmp_path):
        db = _db(tmp_path, [(1, "Honda", "CBR1000RR"), (2, "Ducati", "Panigale V4")])
        assert list(census(db, "Ducati")) == ["Ducati"]

    def test_nothing_unknown_is_an_empty_census_not_an_error(self, tmp_path):
        assert census(_db(tmp_path, [(1, "Honda", "PCX 150")])) == {}
