"""Phase 257 — the two no-model steps: census and entry_check.

**census** is a rule over the whole junction, never a search or a sample —
the reason the figures of record (F139) differ from the loose ones.

**entry_check** checks each finding against the DOCUMENT, not against the
model's account of it. Its known-bad fixture plants one defect per
rejection class and every class must fire; the known-good fixture must
pass. Both are hand-written (255D decision 5): a fixture generated by the
code under test proves only that it agrees with itself.
"""
from __future__ import annotations

import json
import pathlib
import sqlite3
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILL = ROOT / ".claude" / "skills" / "source-transmission"
sys.path.insert(0, str(SKILL))

from census import census  # noqa: E402
from entry_check import REJECTION_IDS, check  # noqa: E402

FIX = SKILL / "fixtures"


def _excerpt_fixture():
    """fixtures/excerpts.json with its documents made absolute, as candidates.py emits them."""
    x = json.loads((FIX / "excerpts.json").read_text(encoding="utf-8"))
    ex = {s: [dict(e, document=str(FIX / e["document"])) for e in v] for s, v in x["excerpts"].items()}
    return ex, x["bad"], x["good"]


class TestEntryCheckKnownBad:
    @pytest.fixture(scope="class")
    def fails(self):
        ex, bad, _ = _excerpt_fixture()
        return (check(json.loads((FIX / "bad.json").read_text(encoding="utf-8")), FIX)
                + check(bad, FIX, ex)
                + check([_wolf("wolf150_noreferrer.txt")], FIX, library=FIX / "library"))

    @pytest.mark.parametrize("rid", REJECTION_IDS)
    def test_this_rejection_fires(self, fails, rid):
        assert any(f.startswith(rid + " ") for f in fails), (
            f"{rid} did not fire on the known-bad fixture: {fails}")

    def test_an_altered_quote_is_caught_by_the_document(self, fails):
        """E3: 6-speed quoted, 5-speed printed. Only reading the document tells."""
        assert any(f.startswith("E3") and "does not contain the quote" in f for f in fails)

    def test_a_doctored_copy_is_caught_by_the_original(self):
        """E3, the F141 case, in isolation: the quote IS in the model's
        saved copy (evidence/gl125_saved.txt) and is NOT in the original
        that copy declares (gl125_spec.html, pinned by sha256). A check
        that reads the copy passes this; only matching against the
        original catches it. Run alone, so no other plant can answer."""
        planted = [f for f in json.loads((FIX / "bad.json").read_text(encoding="utf-8"))
                   if f.get("document") == "evidence/gl125_saved.txt"]
        assert planted, "the doctored-copy plant is missing from bad.json"
        fails = check(planted, FIX)
        assert any(f.startswith("E3") and "does not contain the quote" in f for f in fails), (
            "the doctored copy went through: E3 is reading the copy, not the original")

    def test_a_copy_with_no_declared_original_is_rejected(self, fails):
        """E9: evidence/nosidecar.txt has the quote and the machine name —
        everything a check could want — but no provenance sidecar."""
        assert any(f.startswith("E9") and "provenance.json" in f for f in fails), (
            "a copy with no declared original was accepted")

    def test_a_stale_original_hash_is_rejected(self, fails):
        """E9: the sidecar exists and is well-formed, but its sha256 pins
        the copy's bytes, not the original's."""
        assert any(f.startswith("E9") and "sha256" in f for f in fails), (
            "a provenance pin that does not match the original was accepted")


class TestTheExcerptBinding:
    """E10 — the token redesign's source stage reads candidates.py's
    excerpts and nothing else, so a finding must cite one of them. This is
    what E9 could not do (F141, reopened): every file the model could name
    before, it could also have written."""

    def test_a_document_it_was_not_handed_is_rejected(self):
        ex, bad, _ = _excerpt_fixture()
        fails = check([bad[0]], FIX, ex)
        assert fails and all(f.startswith("E10") for f in fails), fails
        assert "not one of the excerpts" in fails[0]

    def test_a_quote_outside_its_excerpt_is_rejected(self):
        ex, bad, _ = _excerpt_fixture()
        fails = check([bad[1]], FIX, ex)
        assert fails and all(f.startswith("E10") for f in fails), fails
        assert "not inside the excerpts" in fails[0]

    def test_a_finding_from_its_excerpt_passes(self):
        ex, _, good = _excerpt_fixture()
        assert check(good, FIX, ex) == []

    def test_a_library_html_page_is_matched_as_text(self):
        """The source stage now cites library HTML directly (no saved
        copy). Its quote spans `</td><td>`: matched against the raw
        markup it fails; against the text candidates.py showed, it holds."""
        f = {"make": "ZZ", "spelling": "Scout 50", "aliases": ["scout 50"], "outcome": "found",
             "transmission": "cvt", "quote": "Transmission Automatic; V-Matic belt",
             "document": "library/html/zz_scout_spec.html", "page": "spec table",
             "evidence_kind": "maker_spec_page"}
        assert check([f], FIX) == []

    def test_without_excerpts_the_check_is_unchanged(self):
        """E10 applies only where the excerpts are known; the plants are
        otherwise sound findings."""
        _, bad, _ = _excerpt_fixture()
        assert check(bad, FIX) == []


LIB = FIX / "library"


def _lib_finding(spelling, document, quote, kind="owners_manual"):
    return {"make": "ZZ", "spelling": spelling, "aliases": [], "outcome": "found",
            "transmission": "cvt" if ("CVT" in quote or "V-Matic" in quote) else "manual", "quote": quote,
            "document": str(LIB / document), "page": 1, "evidence_kind": kind}


class TestACommonWordMustBeNamedAsAModel:
    """E4, strict for spellings that are ordinary words or bare numbers.
    The real case: Yamaha "Bolt" → the Zuma 125 service manual, whose
    fasteners are bolts and whose belt is a V-belt. Every other check
    passes it: same make, Yamaha's own manual (E2), 'V-belt' (E5), the
    quote on the page (E3), inside the excerpt (E10)."""

    BOLT = ("Bolt", "pdfs/zz_glide125_sm.txt", "Transmission V-belt automatic (CVT)")

    def test_the_bolt_in_a_scooter_manual_is_rejected(self):
        fails = check([_lib_finding(*self.BOLT)], FIX, library=LIB)
        assert fails and all(f.startswith("E4") for f in fails), fails
        assert "as a ZZ model" in fails[0]

    def test_after_the_make_it_is_a_model(self):
        f = _lib_finding("Bolt", "pdfs/zz_range_om.txt", "Transmission  5-speed constant mesh, return shift")
        assert check([f], FIX, library=LIB) == []

    def test_in_the_title_it_is_a_model(self):
        f = _lib_finding("Scout 50", "html/zz_scout_spec.html", "Transmission Automatic; V-Matic belt",
                         "maker_spec_page")
        assert check([f], FIX, library=LIB) == []

    @pytest.mark.parametrize("spelling,weak", [
        ("Bolt", True), ("One", True), ("1000", True), ("RS", True), ("Monster 821", True),
        ("K-Pipe", True), ("ZX-10R", False), ("Wolf CR300i", False), ("Speed Triple", False),
    ])
    def test_which_spellings_are_weak(self, spelling, weak):
        from entry_check import weak_spelling
        assert weak_spelling(spelling) is weak


class TestTheKindComesFromTheIndex:
    """E2 for a library file: library_index's kind, never the model's."""

    @pytest.mark.parametrize("name,kind", [("cyclepedia_zz_trail.txt", "third_party"),
                                           ("models_raw.txt", "crawl_artefact")])
    def test_a_declared_owners_manual_that_is_not_one(self, name, kind):
        f = _lib_finding("Trail 250", name, "Transmission  5-speed constant mesh, return shift")
        fails = check([f], FIX, library=LIB)
        assert any(x.startswith("E2") and kind in x for x in fails), fails

    def test_a_maker_manual_passes_whatever_kind_is_declared(self):
        f = _lib_finding("Trail 250", "zz_trail_om.txt", "Transmission  5-speed constant mesh, return shift",
                         "forum_post")
        assert check([f], FIX, library=LIB) == []

    def test_an_unindexed_library_file_is_not_evidence(self):
        from library_index import kind
        assert kind(LIB / "zz_ranger.json", LIB) == "unindexed"

    @pytest.mark.parametrize("rel,expected", [
        ("v2/cyclepedia_kymco.txt", "third_party"), ("makes_raw.txt", "crawl_artefact"),
        ("models_raw.txt", "crawl_artefact"), ("cp.html", "crawl_artefact"), ("kc.html", "crawl_artefact"),
        ("txt_vespa_lx50_633416.txt", "third_party"), ("nhtsa/docs/15V066_part573.txt", "recall"),
        ("v2/pdf/K-PIPE125-Owners-Manual-1.pdf.txt", "maker_manual"),
        ("v2/sympdf/Wolf_CR300i_Owners_Manual.pdf.txt", "maker_manual"),
        ("honda/grom2025.html", "maker_spec_page"), ("a_new_file_nobody_indexed.txt", "unindexed"),
    ])
    def test_the_real_librarys_rules(self, rel, expected):
        """Pure path rules: these hold without the library on disk."""
        from library_index import LIBRARY, kind
        assert kind(LIBRARY / rel) == expected


class TestEntryCheckKnownGood:
    def test_the_good_fixture_passes(self):
        fails = check(json.loads((FIX / "good.json").read_text(encoding="utf-8")), FIX)
        assert fails == [], fails

    def test_a_declared_on_disk_original_passes(self):
        """The good evidence case with a library original: quote in the
        original HTML (extracted to text by entry_check itself), hash
        correct."""
        findings = [f for f in json.loads((FIX / "good.json").read_text(encoding="utf-8"))
                    if f.get("document") == "evidence/trail_saved.txt"]
        assert check(findings, FIX) == []

    def test_a_declared_url_original_passes_offline(self):
        """A URL original verified through its pinned fetch (fetched_as):
        entry_check never opens a network connection."""
        findings = [f for f in json.loads((FIX / "good.json").read_text(encoding="utf-8"))
                    if f.get("document") == "evidence/gl150_saved.txt"]
        assert check(findings, FIX) == []


def _db(tmp_path, pairs):
    db = tmp_path / "j.db"
    c = sqlite3.connect(db)
    c.execute("CREATE TABLE known_issue_models (issue_id INTEGER, make TEXT, model TEXT)")
    c.executemany("INSERT INTO known_issue_models VALUES (?,?,?)", pairs)
    c.commit(); c.close()
    return db


class TestCensus:
    def test_only_unknown_pairs_are_counted_with_their_rows(self, tmp_path):
        # The unknown Honda is a spelling absent from the real junction, so
        # no batch can ever source it (it was the CBR1000RR, then the CBR929RR).
        from motodiag.knowledge.transmission import resolve_transmission
        assert resolve_transmission("Honda", "ZZ-0 unlisted").provenance == "unknown", (
            "the example machine has been sourced: pick another spelling absent from the junction")
        db = _db(tmp_path, [
            (1, "Honda", "PCX 150"), (2, "Honda", "PCX 150"),      # model-sourced: out
            (3, "Honda", "Africa Twin"),                           # ambiguous: out
            (4, "Honda", "ZZ-0 unlisted"), (5, "Honda", "ZZ-0 unlisted"),  # unknown, 2 rows
            (6, "Ducati", "Panigale V4"),                          # unknown, 1 row
            (7, "Honda", "CBR1000RR"),                             # model-sourced since 257: out
        ])
        assert census(db) == {"Honda": [{"model": "ZZ-0 unlisted", "rows": 2}],
                              "Ducati": [{"model": "Panigale V4", "rows": 1}]}

    def test_the_make_filter(self, tmp_path):
        db = _db(tmp_path, [(1, "Honda", "CBR1000RR"), (2, "Ducati", "Panigale V4")])
        assert list(census(db, "Ducati")) == ["Ducati"]

    def test_nothing_unknown_is_an_empty_census_not_an_error(self, tmp_path):
        assert census(_db(tmp_path, [(1, "Honda", "PCX 150")])) == {}


class TestSpellingsThatCannotBeAMachine:
    """Census classes (the operator's list): bare numbers, another marque's
    name — "Gilera" is under six makes — the make's own name, and junction
    prose (F135). Named lists, each case from the real junction."""

    @pytest.mark.parametrize("make,spelling,cls", [
        ("Ducati", "1000", "bare_number"), ("MV Agusta", "20", "bare_number"),
        ("Aprilia", "1077cc", "bare_number"), ("Ducati", "06", "bare_number"),
        ("Ducati", "Gilera", "other_marque"), ("KTM", "Husqvarna", "other_marque"),
        ("Triumph", "Moto Morini", "other_marque"), ("Ducati", "Guzzi V85", "other_marque"),
        ("Ducati", "MV", "other_marque"), ("MV Agusta", "MV", "marque_name"),
        ("Harley-Davidson", "2020 service manual", "prose"),
        ("Aprilia", "approximately 2016 to 2020", "prose"),
        ("Triumph", "positive earth through 1978", "prose"),
        ("KTM", "S 1000 RR by type code", "prose"),
        # Ducati's engine families: an engine is not a machine (F135 group B).
        ("Ducati", "Testastretta", "engine_family"), ("Ducati", "Desmoquattro", "engine_family"),
        ("Ducati", "Superquadro", "engine_family"), ("Ducati", "Desmodue", "engine_family"),
        ("Ducati", "Desmoquattro 16-valve", "engine_family"), ("Ducati", "Testastretta MY2010", "engine_family"),
        ("Ducati", "998 Testastretta", "engine_family"),
        # Another make's machine, attached by one shared row (#912, #886).
        ("Ducati", "S 1000 XR", "other_make_model"), ("Aprilia", "S 1000 XR", "other_make_model"),
        ("Moto Guzzi", "S 1000 XR", "other_make_model"), ("Triumph", "S 1000 XR", "other_make_model"),
        ("KTM", "S 1000 XR", "other_make_model"), ("KTM", "Testastretta MY2010", "other_make_model"),
        ("BMW", "Testastretta MY2010", "other_make_model"), ("MV Agusta", "Testastretta MY2010", "other_make_model"),
        # Multi-make rows #4593/#4596 ('Kymco, SYM') and #4603 ('Yamaha, Kymco,
        # SYM, Genuine') pair every model with every make (F142).
        ("Kymco", "Jet 14", "other_make_model"), ("Kymco", "Fiddle 4", "other_make_model"),
        ("Kymco", "Wolf CR300i", "other_make_model"), ("SYM", "X-Town 300", "other_make_model"),
        ("Kymco", "XC50", "other_make_model"), ("SYM", "XC50", "other_make_model"),
        ("Genuine", "XC50", "other_make_model"),
    ])
    def test_the_class(self, make, spelling, cls):
        from census import not_a_machine
        assert not_a_machine(make, spelling) == cls

    @pytest.mark.parametrize("make,spelling", [
        ("Moto Guzzi", "Guzzi V85"), ("Yamaha", "Bolt"), ("Kawasaki", "ZX-10R"),
        ("SYM", "SYMBA 110"), ("Ducati", "1260 S"), ("Triumph", "Speed Triple"),
        ("MV Agusta", "Brutale"), ("KTM", "LC8"), ("Honda", "MVX250F"),
        # Machines whose name IS a number (bug fix #1: db920bb's shape rule
        # classed every one of these bare_number and never searched them).
        ("Ducati", "916"), ("Ducati", "996"), ("Ducati", "998"), ("Ducati", "999"),
        ("Ducati", "1098"), ("Ducati", "1198"), ("Ducati", "1299"), ("Ducati", "848"),
        ("Ducati", "749"), ("Ducati", "959"), ("Ducati", "899"), ("Ducati", "748"),
        ("Ducati", "851"), ("Ducati", "888"), ("Vespa", "946"), ("Piaggio", "946"),
        ("MV Agusta", "675"), ("MV Agusta", "910"), ("MV Agusta", "982"), ("MV Agusta", "1078"),
        ("MV Agusta", "750"), ("MV Agusta", "998"),
        # The entries above are make-scoped: under its own make the BMW is a
        # machine, and Ducati's own machines stay machines.
        ("BMW", "S 1000 XR"), ("Ducati", "Panigale V4"), ("Ducati", "Multistrada 1200"),
        ("Ducati", "Monster S4R"),
        # The true make keeps its machine (operator, 2026-09-23).
        ("SYM", "Jet 14"), ("SYM", "Fiddle 4"), ("Kymco", "X-Town 300"), ("Yamaha", "XC50"),
        ("SYM", "Wolf CR300i"),
    ])
    def test_a_machine_name_is_not_classed(self, make, spelling):
        """Including a marque's own model under its own marque, and a
        spelling that merely starts with the letters of one (SYMBA)."""
        from census import not_a_machine
        assert not_a_machine(make, spelling) is None

    def test_the_census_reports_them_as_their_own_count(self, tmp_path):
        from census import classes
        db = _db(tmp_path, [(1, "Ducati", "1000"), (2, "Ducati", "Gilera"),
                            (3, "Ducati", "Panigale V4"), (4, "Ducati", "2020 service manual")])
        assert classes(db) == {"Ducati": {"bare_number": ["1000"], "other_marque": ["Gilera"],
                                          "machine": ["Panigale V4"], "prose": ["2020 service manual"]}}


WOLF_QUOTE = ("Squeeze the clutch lever fully, operate change pedal to the proper position, "
              "then release the clutch lever to make a gear change.")


def _wolf(name, make="SYM"):
    """A finding citing an acquired copy of the SYM Wolf 150 manual."""
    return {"make": make, "spelling": "Wolf 150", "aliases": [], "outcome": "found", "transmission": "manual",
            "quote": WOLF_QUOTE, "document": str(FIX / "library" / "acquired" / "SYM" / name), "page": 18,
            "evidence_kind": "owners_manual"}


class TestAcquiredProvenance:
    """E11 — the Wolf 150 case. SYM USA's own maintenance-guide page links
    the Wolf 150 owner's manual on Dropbox (the library's `sym_mg.html`;
    the Dropbox PDF is byte-identical to `v2/sympdf/Wolf150_Owner_Manual.pdf`).
    Dropbox is not a SYM host, so the file counts only through its referrer:
    a page on a SYM host, itself in the library, unchanged, linking to it."""

    LIB = FIX / "library"

    def test_the_wolf_150_manual_counts_through_sym_usas_page(self):
        assert check([_wolf("wolf150_owner_manual.txt")], FIX, library=self.LIB) == []

    @pytest.mark.parametrize("name,why", [
        ("wolf150_noreferrer.txt", "no referrer on one"),
        ("wolf150_forumref.txt", "is not on a SYM host"),
        ("wolf150_unlinked.txt", "does not link to"),
        ("wolf150_staleref.txt", "has changed since it was recorded"),
        ("wolf150_tampered.txt", "no longer hashes"),
        ("wolf150_nosidecar.txt", "no readable"),
    ])
    def test_each_broken_provenance_is_rejected(self, name, why):
        fails = check([_wolf(name)], FIX, library=self.LIB)
        assert any(f.startswith("E11") and why in f for f in fails), fails

    def test_the_referrer_must_be_the_findings_makes(self):
        """SYM's page does not vouch for a Kymco finding."""
        fails = check([_wolf("wolf150_owner_manual.txt", make="Kymco")], FIX, library=self.LIB)
        assert any(f.startswith("E11") for f in fails), fails

    def test_a_document_on_the_makers_own_host_needs_no_referrer(self):
        f = {"make": "Genuine", "spelling": "Buddy 125", "aliases": [], "outcome": "found", "transmission": "cvt",
             "quote": "Transmission: automatic, V-belt (CVT)",
             "document": str(self.LIB / "acquired" / "Genuine" / "buddy125_owners_manual.txt"), "page": 1,
             "evidence_kind": "owners_manual"}
        assert check([f], FIX, library=self.LIB) == []

    @pytest.mark.parametrize("url,make,ok", [
        ("https://sym-usa.com/x", "SYM", True), ("https://www.sym-global.com/x", "SYM", True),
        ("https://sym-usa.com.evil.example/x", "SYM", False), ("https://notsym-usa.com/", "SYM", False),
        ("https://www.dropbox.com/s/x", "SYM", False),
    ])
    def test_maker_host_is_the_host_or_a_subdomain(self, url, make, ok):
        from library_index import maker_host
        assert maker_host(url, make) is ok

    @pytest.mark.parametrize("url,make,ok", [
        # The hosts each maker's own owner's manual PDF was served from (operator, 2026-09-23).
        ("https://library.ymcapps.net/library/om/contents/pdf/10/5YR-F8199-15_02.pdf", "Yamaha", True),
        # KTM's CDN is not a KTM host (operator): its PDFs pass only through ktm.com's JSON.
        ("https://azwecdnepstoragewebsiteuploads.azureedge.net/24_3214961_en_OM.pdf", "KTM", False),
        # Lookalikes must still fail.
        ("https://yamaha-motor.co.jp.example.com/x.pdf", "Yamaha", False),
        ("https://library.ymcapps.net.example.com/x.pdf", "Yamaha", False),
        ("https://evillibrary.ymcapps.net/x.pdf", "Yamaha", False),
        ("https://ymcapps.net/x.pdf", "Yamaha", False),
        ("https://azwecdnepstoragewebsiteuploads.azureedge.net.example.com/x.pdf", "KTM", False),
        ("https://otherstorage.azureedge.net/x.pdf", "KTM", False),
        # Seen, but not serving a manual: the API host, Triumph's 403 portal.
        ("https://parts.yamaha-motor.co.jp/ypec_b2c/services/omb2c/model_list/", "Yamaha", False),
        ("https://api.triumphtechnicalinformation.com/documents/x/download", "Triumph", False),
        # A host added for one make does not vouch for another.
        ("https://library.ymcapps.net/x.pdf", "KTM", False),
    ])
    def test_the_owners_manual_hosts(self, url, make, ok):
        from library_index import maker_host
        assert maker_host(url, make) is ok

    @pytest.mark.parametrize("make,rel", [
        ("Yamaha", "acquired/Yamaha/library_om_contents_pdf_10_5YR-F8199-15_02.pdf"),
        ("KTM", "acquired/KTM/24_3214961_en_OM.pdf"),
    ])
    def test_the_fetched_manuals_pass_e11(self, make, rel):
        """The real PDFs and their derived texts, in the operator's library."""
        from entry_check import acquired_provenance
        from library_index import LIBRARY
        doc = LIBRARY / rel
        if not doc.is_file():
            pytest.skip(f"{rel} is not in this machine's library")
        assert acquired_provenance(doc, LIBRARY, make, "t") == []
        assert acquired_provenance(doc.with_name(doc.name + ".txt"), LIBRARY, make, "t") == []


class TestAJsonReferrerLinksByExactValue:
    """Operator, 2026-09-23: KTM's owner's manuals live on a generic Azure
    CDN host, which is not a KTM host. They pass E11 through ktm.com's own
    bikemanuals.manuals.json, which names each PDF by exact URL — the way
    SYM's Dropbox manual passes through SYM's page."""

    CDN = "https://azwecdnepstoragewebsiteuploads.azureedge.net/"
    AT = ("https://www.ktm.com/en-us/service/manuals/_jcr_content/root/responsivegrid_1_col/"
          "bikemanuals.manuals.json?modelName=390+Duke+2024")
    # The shape of ktm.com's response (two of its rows, verbatim).
    PAGE = json.dumps({"status": {"success": True, "messages": []}, "data": {"manuals": [
        {"modelName": "390 Duke 2024", "title": "390 Duke 2024 EU (en) - 2024",
         "link": CDN + "24_3214960_en_OM.pdf"},
        {"modelName": "390 Duke 2024", "title": "390 Duke 2024 US (en) - 2024",
         "link": CDN + "24_3214961_en_OM.pdf"}]}}, indent=2).encode()

    @pytest.mark.parametrize("url,ok", [
        (CDN + "24_3214961_en_OM.pdf", True),
        (CDN + "24_3214960_en_OM.pdf", True),
        (CDN + "25_9999999_en_OM.pdf", False),                    # same CDN, not listed
        ("https://azwecdnepstoragewebsiteuploads.azureedge.net.example.com/24_3214961_en_OM.pdf", False),
        ("https://otherstorage.azureedge.net/24_3214961_en_OM.pdf", False),
        ("24_3214961_en_OM.pdf", False),                          # exact: a value is never resolved
    ])
    def test_a_json_value_links_by_exact_url(self, url, ok):
        from entry_check import links_to
        assert links_to(self.PAGE, self.AT, url) is ok

    def test_a_relative_json_value_is_not_resolved(self):
        from entry_check import links_to
        page = json.dumps({"link": "/files/manual.pdf"}).encode()
        assert not links_to(page, "https://www.ktm.com/x.json", "https://www.ktm.com/files/manual.pdf")

    def test_html_is_still_read_as_html(self):
        from entry_check import links_to
        page = b'<a href="/content/manual.pdf">Manual</a>'
        assert links_to(page, "https://www.ktm.com/service.html", "https://www.ktm.com/content/manual.pdf")

    def test_the_real_390_duke_manual_passes_and_an_unlisted_cdn_file_fails(self, tmp_path):
        """On the real files: the saved PDF passes E11 through ktm.com's JSON;
        the same PDF recorded under a CDN URL the JSON does not list fails."""
        import shutil
        from entry_check import acquired_provenance
        from library_index import LIBRARY
        doc = LIBRARY / "acquired" / "KTM" / "24_3214961_en_OM.pdf"
        if not doc.is_file():
            pytest.skip("the KTM manual is not in this machine's library")
        assert acquired_provenance(doc, LIBRARY, "KTM", "t") == []
        side = json.loads((doc.parent / (doc.name + ".acquired.json")).read_text())
        ref = LIBRARY / side["referrer"]["path"]
        lib = tmp_path / "lib"
        for p in (doc, ref):
            (lib / p.relative_to(LIBRARY)).parent.mkdir(parents=True, exist_ok=True)
            shutil.copy(p, lib / p.relative_to(LIBRARY))
        moved = dict(side, url=self.CDN + "25_9999999_en_OM.pdf", final_url=self.CDN + "25_9999999_en_OM.pdf")
        (lib / "acquired" / "KTM" / (doc.name + ".acquired.json")).write_text(json.dumps(moved))
        fails = acquired_provenance(lib / "acquired" / "KTM" / doc.name, lib, "KTM", "t")
        assert fails and "does not link to" in fails[0], fails


class TestTheReferrerLinkIsResolvedLikeABrowser:
    """A page saved with 'Save Page As' keeps relative links; E11 resolves
    each href/src against the page's own URL. The same page must not vouch
    for a file it does not link."""

    PAGE = (b'<html><a href="/content/dam/manuals/Panigale V4 OM.pdf">OM</a>'
            b'<a href="../spec/v4s.pdf">spec</a><img src="https://cdn.ducati.com/x.png"></html>')
    AT = "https://www.ducati.com/us/en/owners/owner-manuals"

    @pytest.mark.parametrize("url,ok", [
        ("https://www.ducati.com/content/dam/manuals/Panigale V4 OM.pdf", True),
        ("https://www.ducati.com/content/dam/manuals/Panigale%20V4%20OM.pdf", True),
        ("https://www.ducati.com/us/en/spec/v4s.pdf", True),
        ("https://www.ducati.com/content/dam/manuals/Monster OM.pdf", False),
        ("https://evil.example/content/dam/manuals/Panigale V4 OM.pdf", False),
    ])
    def test_relative_and_encoded_links(self, url, ok):
        from entry_check import links_to
        assert links_to(self.PAGE, self.AT, url) is ok


class TestNamesModel:
    """entry_check.names_model — the words of the model in a run, not
    followed by a variant word (VARIANT_TOKENS). Shapes from this phase."""

    @pytest.mark.parametrize("text,spelling,named", [
        ("KTM 1290 SUPER DUKE GT specifications", "1290 Super Duke", False),
        ("the 1290 Super Duke R is", "1290 Super Duke R", True),
        ("F 800 GS rider manual", "F800", False),
        ("Model WOLF CR 300i", "Wolf CR300i", True),
        ("Zero SR/S", "SR", False),
        ("Zero SR and SR/S", "SR", True),
        ("2025 Honda Grom Specifications", "Grom", True),
        ("Grom ABS (MSX125AS)", "Grom", True),
        ("K-PIPE 125 owner's manual", "K-Pipe", True),
        ("the Speed Triple 1200 RS", "Speed Triple 1200", False),
    ])
    def test_named(self, text, spelling, named):
        from entry_check import names_model
        assert names_model(text, spelling) is named


class TestTheAbsException:
    """Operator decision 2026-09-23, named and narrow: a page for
    '<exact base model> ABS' may source the base model, and the entry
    records that it came from the ABS edition. Nothing else qualifies —
    above all DCT, a transmission: the one variant that changes the answer."""

    @pytest.mark.parametrize("text,spelling", [
        ("2026 SV650 ABS specifications", "SV650"),
        ("2026 Kawasaki Z900 ABS", "Z900"),
        ("Ninja H2 ABS | Hypersport", "Ninja H2"),
    ])
    def test_an_abs_edition_page_sources_its_base_model(self, text, spelling):
        from entry_check import abs_edition, names_model
        assert names_model(text, spelling) and abs_edition(text, spelling)

    @pytest.mark.parametrize("text,spelling", [
        ("2019 Suzuki SV650X specifications", "SV650"),
        ("2026 Ninja ZX-10RR", "ZX-10R"),
        ("2025 V-Strom 650XT Adventure", "V-Strom 650"),
        ("2026 CRF1100L Africa Twin DCT", "Africa Twin"),
        ("MT-09 Y-AMT specifications", "MT-09"),
        ("CB650R E-Clutch", "CB650R"),
        ("2026 Z900 SE ABS", "Z900"),
        ("2026 Ninja H2 Carbon ABS", "Ninja H2"),
    ])
    def test_nothing_else_sources_its_base(self, text, spelling):
        from entry_check import abs_edition, names_model
        assert not names_model(text, spelling) and not abs_edition(text, spelling)


class TestE12ManualNeedsMechanismEvidence:
    """Operator decision 2026-09-23. Refute killed Ninja 650's 'Transmission
    6-speed' (a DCT or Y-AMT is a six-speed too) and had kept the same kind
    of quote the batch before: the standard drifted, so it is a rule. A
    `manual` classification needs a quote naming a rider-operated clutch, a
    foot-shift pattern, or the word 'manual'. A gear count, 'constant mesh'
    or 'close-ratio' alone is not mechanism evidence."""

    @pytest.mark.parametrize("quote", [
        "Transmission 6-speed, return shift Final Drive Sealed chain",          # ZX-6R (known-good)
        "Transmission 5-speed, return shift with wet multi-disc manual clutch",  # KLR650
        "Transmission.......................... 4-speed, foot shift",           # K-Pipe
        "Transmission Manual; 5 speeds Clutch Multiplate wet",                   # Grom
        "Squeeze the clutch lever fully, operate change pedal to the proper position",
        "Compact, five-speed transmission utilizes a cable-operated clutch",    # DR-Z400S
        "With a light pull, the clutch feeds engine power to the smooth-shifting five-speed transmission",
        "a hydraulically actuated clutch and a six-speed gearbox",
    ])
    def test_mechanism_evidence_passes(self, quote):
        from entry_check import manual_evidence
        assert manual_evidence(quote)

    @pytest.mark.parametrize("quote", [
        "Transmission 6-speed Final Drive Sealed chain",                         # Ninja 650 (known-bad)
        "The close-ratio, six-speed transmission features carefully selected ratios",   # SV650, V-Strom 650
        "A wide-ratio, constant-mesh five-speed transmission features a high fifth gear ratio",  # M109R
        "The six-speed, close-ratio transmission have high gear ratios in first and sixth gear to smooth the shift action",  # V-Strom 1050
        "See the owner's manual for the six-speed transmission",                # 'manual' as a document
        "A back-torque-limiting clutch contributes to smoother downshifting",   # a clutch, not rider-operated
    ])
    def test_a_gear_count_is_not_mechanism_evidence(self, quote):
        from entry_check import manual_evidence
        assert not manual_evidence(quote)

    def test_e12_rejects_the_ninja_650_shape_and_passes_the_zx6r_shape(self):
        bad = _lib_finding("Comet 700", "pdfs/zz_comet700_om.txt", "Transmission")
        bad["quote"] = "The Comet 700 clutch lever and gear shift pedal, item 1."
        assert not [x for x in check([bad], FIX, library=LIB) if x.startswith("E12")]
        f = _lib_finding("Blade 650", "pdfs/zz_blade650abs_spec.txt",
                         "The close-ratio, six-speed transmission features carefully selected ratios.")
        assert any(x.startswith("E12") for x in check([f], FIX, library=LIB))

    def test_only_manual_is_held_to_it(self):
        f = _lib_finding("Glide 125", "pdfs/zz_glide_quickref.txt", "Transmission  V-belt automatic (CVT)")
        assert not [x for x in check([f], FIX, library=LIB) if x.startswith("E12")]


SV650_PULL = ("The multi-plate clutch has precise push rod actuation of the pressure plate "
              "for a light pull and consistent release point.")
VSTROM_PULL = ("The multi-plate clutch has precise push rod actuation of the pressure plate "
               "for a light lever pull and a consistent release point.")


class TestE12ClosesTheAutomatedGap:
    """Operator decision 2026-09-23, before Yamaha (Y-AMT) and Honda (DCT):
    E12 must not accept a sentence that carries an automated-transmission
    marker or a negation governing its clutch/shift term — and the clutch
    pull window widens to one sentence (a noun 'pull', not the engine's)."""

    @pytest.mark.parametrize("quote", [
        "Y-AMT eliminates the clutch lever and shift pedal",
        "Dual Clutch Transmission lets you pull away without a clutch lever; manual mode shifts with paddles",
        "the slipper clutch smooths downshifts while the engine pulls hard from low rpm",
        "there's no clutch lever to pull",
        "The Yamaha Automated Manual Transmission shifts for you",
        "Switch to manual mode and shift with the paddle shifters on the DCT",
        "The clutchless Y-AMT has no shift pedal",
        "lets the rider start the motorcycle without pulling in the clutch lever when the transmission is in neutral",
        "A race-proven back-torque-limiting clutch contributes to smoother downshifting",   # GSX-R
        "Three-way adjustable foot pegs, adjustable shift lever",                         # GSX-R
        # A semicolon does not end the DCT's sentence: the half after it is clean.
        "Honda's Dual Clutch Transmission shifts on its own; manual shifting uses the handlebar buttons",
        # A DCT's "manual mode", with no other marker in the sentence.
        "Switch to manual mode and shift with the handlebar buttons",
    ])
    def test_known_bad(self, quote):
        from entry_check import manual_evidence
        assert not manual_evidence(quote)

    @pytest.mark.parametrize("quote", [
        SV650_PULL, VSTROM_PULL,
        "Transmission 6-speed, return shift Final Drive Sealed chain",
        "Transmission 5-speed, return shift with wet multi-disc manual clutch",
        "Transmission Manual; 5 speeds Clutch Multiplate wet",
        "Start engine, squeeze the clutch lever fully, push shift pedal down to engage the 1st gear",
        "With a light pull, the clutch feeds engine power to the smooth-shifting five-speed transmission",
    ])
    def test_known_good(self, quote):
        from entry_check import manual_evidence
        assert manual_evidence(quote)


class TestTheWidenedPullOnTheRealPages:
    """The widened clutch-pull window, on the saved Suzuki pages' own
    sentences: SV650 and V-Strom 650 qualify; no GSX-R sentence does."""

    @pytest.mark.parametrize("sentence,ok", [
        (SV650_PULL, True), (VSTROM_PULL, True),
        ("A race-proven, back-torque-limiting clutch contributes to smoother downshifting and corner entry.", False),
        ("The Suzuki Clutch Assist System (SCAS) multi-plate, wet clutch functions like a slipper clutch "
         "during downshifts while increasing plate pressure during acceleration.", False),
        ("Clutch Wet, multi-plate type", False),
    ])
    def test_suzuki_sentences(self, sentence, ok):
        from entry_check import manual_evidence
        assert manual_evidence(sentence) is ok


class TestBugFix5E12ReadsRealTypography:
    """Bug fix #5 (operator, 2026-09-23): E12's negation and document-title
    rules read only plain-typed text. Each of these must fail E12."""

    @pytest.mark.parametrize("quote", [
        # Real BMW text, typographic apostrophe: "Rider’s Manual" names the
        # document, not a gearbox (BMW prints it this way 55 times).
        "Location of type plate On rear frame on left ( b Rider’s Manual, Chapter 1)",
        # Constructed; to be replaced by Honda's own E-Clutch wording once acquired.
        "With Honda E-Clutch you don't have to operate the clutch lever when starting or stopping.",
        # The negation comes after the term.
        "The clutch lever is not required when shifting.",
        # Constructed; "cannot" has no word boundary before its "not", so the
        # bare-word list never saw it (break-it survivor until this case).
        "You cannot operate the clutch lever while the system is active.",
        # Constructed; the same apostrophe in its typographic form.
        "You don’t have to operate the clutch lever when starting.",
    ])
    def test_it_fails_e12(self, quote):
        from entry_check import manual_evidence
        assert not manual_evidence(quote)


class TestE12TheWordManualNeedsAGearbox:
    """Operator decision 2026-09-23, before owner's manuals: the word "manual"
    counts only within three words of transmission, gearbox, gear shift or a
    gear count. Owner's manuals say "manual choke", "manual fuel valve",
    "manual adjustment"; the Triumph run's dry run sent five spellings on one
    suspension sentence."""

    @pytest.mark.parametrize("quote", [
        # Real: triumphmotorcycles.com, Speed Triple 1200 RS page.
        "For those who prefer a fixed setup, manual adjustment of compression and rebound damping "
        "is also available via the instrument menu.",
        # Real: Honda owner's manual excerpt (Honda_20260923_155534).
        "Follow all load limits and other loading guidelines in this manual.",
        # Constructed, the operator's examples.
        "Pull the manual choke knob fully out.",
        "Turn the manual fuel valve to ON.",
        # Constructed: a gearbox term, but four words or more away.
        "Pull the manual choke knob fully out before you select the transmission.",
    ])
    def test_manual_away_from_a_gearbox_fails(self, quote):
        from entry_check import manual_evidence
        assert not manual_evidence(quote)

    @pytest.mark.parametrize("quote", [
        "Manual transmission",                                                  # transmission
        "Manual gearbox The motorcycle can be started in the neutral position",  # gearbox (BMW K 1200 S)
        "The manual gear shift sits by the left footpeg",                       # gear shift (constructed)
        "A six-speed manual",                                                   # a gear count (constructed)
        "6-speed manual gearbox",
        "Transmission  Manual; 5 speeds",                                       # Honda Grom
        "Manual transmission 6-speed with claw shift and integral…",            # BMW K 1200 RS
    ])
    def test_manual_beside_a_gearbox_passes(self, quote):
        from entry_check import manual_evidence
        assert manual_evidence(quote)
