"""Phase 257 — the two no-model steps: census and entry_check.

**census** is a rule over the whole junction, never a search or a sample —
the reason the figures of record (F139) differ from the loose ones.

**entry_check** checks each finding against the DOCUMENT, not against the
model's account of it. Its known-bad fixture plants one defect per
rejection class and every class must fire; the known-good fixture must
pass. Both are hand-written (255D decision 5): a fixture generated by the
code under test proves only that it agrees with itself.
"""
from __future__ import annotations

import json
import pathlib
import sqlite3
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILL = ROOT / ".claude" / "skills" / "source-transmission"
sys.path.insert(0, str(SKILL))

from census import census  # noqa: E402
from entry_check import REJECTION_IDS, check  # noqa: E402

FIX = SKILL / "fixtures"


def _excerpt_fixture():
    """fixtures/excerpts.json with its documents made absolute, as candidates.py emits them."""
    x = json.loads((FIX / "excerpts.json").read_text(encoding="utf-8"))
    ex = {s: [dict(e, document=str(FIX / e["document"])) for e in v] for s, v in x["excerpts"].items()}
    return ex, x["bad"], x["good"]


class TestEntryCheckKnownBad:
    @pytest.fixture(scope="class")
    def fails(self):
        ex, bad, _ = _excerpt_fixture()
        return (check(json.loads((FIX / "bad.json").read_text(encoding="utf-8")), FIX)
                + check(bad, FIX, ex)
                + check([_wolf("wolf150_noreferrer.txt")], FIX, library=FIX / "library"))

    @pytest.mark.parametrize("rid", REJECTION_IDS)
    def test_this_rejection_fires(self, fails, rid):
        assert any(f.startswith(rid + " ") for f in fails), (
            f"{rid} did not fire on the known-bad fixture: {fails}")

    def test_an_altered_quote_is_caught_by_the_document(self, fails):
        """E3: 6-speed quoted, 5-speed printed. Only reading the document tells."""
        assert any(f.startswith("E3") and "does not contain the quote" in f for f in fails)

    def test_a_doctored_copy_is_caught_by_the_original(self):
        """E3, the F141 case, in isolation: the quote IS in the model's
        saved copy (evidence/gl125_saved.txt) and is NOT in the original
        that copy declares (gl125_spec.html, pinned by sha256). A check
        that reads the copy passes this; only matching against the
        original catches it. Run alone, so no other plant can answer."""
        planted = [f for f in json.loads((FIX / "bad.json").read_text(encoding="utf-8"))
                   if f.get("document") == "evidence/gl125_saved.txt"]
        assert planted, "the doctored-copy plant is missing from bad.json"
        fails = check(planted, FIX)
        assert any(f.startswith("E3") and "does not contain the quote" in f for f in fails), (
            "the doctored copy went through: E3 is reading the copy, not the original")

    def test_a_copy_with_no_declared_original_is_rejected(self, fails):
        """E9: evidence/nosidecar.txt has the quote and the machine name —
        everything a check could want — but no provenance sidecar."""
        assert any(f.startswith("E9") and "provenance.json" in f for f in fails), (
            "a copy with no declared original was accepted")

    def test_a_stale_original_hash_is_rejected(self, fails):
        """E9: the sidecar exists and is well-formed, but its sha256 pins
        the copy's bytes, not the original's."""
        assert any(f.startswith("E9") and "sha256" in f for f in fails), (
            "a provenance pin that does not match the original was accepted")


class TestTheExcerptBinding:
    """E10 — the token redesign's source stage reads candidates.py's
    excerpts and nothing else, so a finding must cite one of them. This is
    what E9 could not do (F141, reopened): every file the model could name
    before, it could also have written."""

    def test_a_document_it_was_not_handed_is_rejected(self):
        ex, bad, _ = _excerpt_fixture()
        fails = check([bad[0]], FIX, ex)
        assert fails and all(f.startswith("E10") for f in fails), fails
        assert "not one of the excerpts" in fails[0]

    def test_a_quote_outside_its_excerpt_is_rejected(self):
        ex, bad, _ = _excerpt_fixture()
        fails = check([bad[1]], FIX, ex)
        assert fails and all(f.startswith("E10") for f in fails), fails
        assert "not inside the excerpts" in fails[0]

    def test_a_finding_from_its_excerpt_passes(self):
        ex, _, good = _excerpt_fixture()
        assert check(good, FIX, ex) == []

    def test_a_library_html_page_is_matched_as_text(self):
        """The source stage now cites library HTML directly (no saved
        copy). Its quote spans `</td><td>`: matched against the raw
        markup it fails; against the text candidates.py showed, it holds."""
        f = {"make": "ZZ", "spelling": "Scout 50", "aliases": ["scout 50"], "outcome": "found",
             "transmission": "cvt", "quote": "Transmission Automatic; V-Matic belt",
             "document": "library/html/zz_scout_spec.html", "page": "spec table",
             "evidence_kind": "maker_spec_page"}
        assert check([f], FIX) == []

    def test_without_excerpts_the_check_is_unchanged(self):
        """E10 applies only where the excerpts are known; the plants are
        otherwise sound findings."""
        _, bad, _ = _excerpt_fixture()
        assert check(bad, FIX) == []


LIB = FIX / "library"


def _lib_finding(spelling, document, quote, kind="owners_manual"):
    return {"make": "ZZ", "spelling": spelling, "aliases": [], "outcome": "found",
            "transmission": "cvt" if "CVT" in quote else "manual", "quote": quote,
            "document": str(LIB / document), "page": 1, "evidence_kind": kind}


class TestACommonWordMustBeNamedAsAModel:
    """E4, strict for spellings that are ordinary words or bare numbers.
    The real case: Yamaha "Bolt" → the Zuma 125 service manual, whose
    fasteners are bolts and whose belt is a V-belt. Every other check
    passes it: same make, Yamaha's own manual (E2), 'V-belt' (E5), the
    quote on the page (E3), inside the excerpt (E10)."""

    BOLT = ("Bolt", "pdfs/zz_glide125_sm.txt", "Transmission V-belt automatic (CVT)")

    def test_the_bolt_in_a_scooter_manual_is_rejected(self):
        fails = check([_lib_finding(*self.BOLT)], FIX, library=LIB)
        assert fails and all(f.startswith("E4") for f in fails), fails
        assert "as a ZZ model" in fails[0]

    def test_after_the_make_it_is_a_model(self):
        f = _lib_finding("Bolt", "pdfs/zz_range_om.txt", "Transmission  5-speed constant mesh, return type")
        assert check([f], FIX, library=LIB) == []

    def test_in_the_title_it_is_a_model(self):
        f = _lib_finding("Scout 50", "html/zz_scout_spec.html", "Transmission Automatic; V-Matic belt",
                         "maker_spec_page")
        assert check([f], FIX, library=LIB) == []

    @pytest.mark.parametrize("spelling,weak", [
        ("Bolt", True), ("One", True), ("1000", True), ("RS", True), ("Monster 821", True),
        ("K-Pipe", True), ("ZX-10R", False), ("Wolf CR300i", False), ("Speed Triple", False),
    ])
    def test_which_spellings_are_weak(self, spelling, weak):
        from entry_check import weak_spelling
        assert weak_spelling(spelling) is weak


class TestTheKindComesFromTheIndex:
    """E2 for a library file: library_index's kind, never the model's."""

    @pytest.mark.parametrize("name,kind", [("cyclepedia_zz_trail.txt", "third_party"),
                                           ("models_raw.txt", "crawl_artefact")])
    def test_a_declared_owners_manual_that_is_not_one(self, name, kind):
        f = _lib_finding("Trail 250", name, "Transmission  5-speed constant mesh, return type")
        fails = check([f], FIX, library=LIB)
        assert any(x.startswith("E2") and kind in x for x in fails), fails

    def test_a_maker_manual_passes_whatever_kind_is_declared(self):
        f = _lib_finding("Trail 250", "zz_trail_om.txt", "Transmission  5-speed constant mesh, return type",
                         "forum_post")
        assert check([f], FIX, library=LIB) == []

    def test_an_unindexed_library_file_is_not_evidence(self):
        from library_index import kind
        assert kind(LIB / "zz_ranger.json", LIB) == "unindexed"

    @pytest.mark.parametrize("rel,expected", [
        ("v2/cyclepedia_kymco.txt", "third_party"), ("makes_raw.txt", "crawl_artefact"),
        ("models_raw.txt", "crawl_artefact"), ("cp.html", "crawl_artefact"), ("kc.html", "crawl_artefact"),
        ("txt_vespa_lx50_633416.txt", "third_party"), ("nhtsa/docs/15V066_part573.txt", "recall"),
        ("v2/pdf/K-PIPE125-Owners-Manual-1.pdf.txt", "maker_manual"),
        ("v2/sympdf/Wolf_CR300i_Owners_Manual.pdf.txt", "maker_manual"),
        ("honda/grom2025.html", "maker_spec_page"), ("a_new_file_nobody_indexed.txt", "unindexed"),
    ])
    def test_the_real_librarys_rules(self, rel, expected):
        """Pure path rules: these hold without the library on disk."""
        from library_index import LIBRARY, kind
        assert kind(LIBRARY / rel) == expected


class TestEntryCheckKnownGood:
    def test_the_good_fixture_passes(self):
        fails = check(json.loads((FIX / "good.json").read_text(encoding="utf-8")), FIX)
        assert fails == [], fails

    def test_a_declared_on_disk_original_passes(self):
        """The good evidence case with a library original: quote in the
        original HTML (extracted to text by entry_check itself), hash
        correct."""
        findings = [f for f in json.loads((FIX / "good.json").read_text(encoding="utf-8"))
                    if f.get("document") == "evidence/trail_saved.txt"]
        assert check(findings, FIX) == []

    def test_a_declared_url_original_passes_offline(self):
        """A URL original verified through its pinned fetch (fetched_as):
        entry_check never opens a network connection."""
        findings = [f for f in json.loads((FIX / "good.json").read_text(encoding="utf-8"))
                    if f.get("document") == "evidence/gl150_saved.txt"]
        assert check(findings, FIX) == []


def _db(tmp_path, pairs):
    db = tmp_path / "j.db"
    c = sqlite3.connect(db)
    c.execute("CREATE TABLE known_issue_models (issue_id INTEGER, make TEXT, model TEXT)")
    c.executemany("INSERT INTO known_issue_models VALUES (?,?,?)", pairs)
    c.commit(); c.close()
    return db


class TestCensus:
    def test_only_unknown_pairs_are_counted_with_their_rows(self, tmp_path):
        db = _db(tmp_path, [
            (1, "Honda", "PCX 150"), (2, "Honda", "PCX 150"),      # model-sourced: out
            (3, "Honda", "Africa Twin"),                           # ambiguous: out
            (4, "Honda", "CBR1000RR"), (5, "Honda", "CBR1000RR"),  # unknown, 2 rows
            (6, "Ducati", "Panigale V4"),                          # unknown, 1 row
        ])
        assert census(db) == {"Honda": [{"model": "CBR1000RR", "rows": 2}],
                              "Ducati": [{"model": "Panigale V4", "rows": 1}]}

    def test_the_make_filter(self, tmp_path):
        db = _db(tmp_path, [(1, "Honda", "CBR1000RR"), (2, "Ducati", "Panigale V4")])
        assert list(census(db, "Ducati")) == ["Ducati"]

    def test_nothing_unknown_is_an_empty_census_not_an_error(self, tmp_path):
        assert census(_db(tmp_path, [(1, "Honda", "PCX 150")])) == {}


class TestSpellingsThatCannotBeAMachine:
    """Census classes (the operator's list): bare numbers, another marque's
    name — "Gilera" is under six makes — the make's own name, and junction
    prose (F135). Named lists, each case from the real junction."""

    @pytest.mark.parametrize("make,spelling,cls", [
        ("Ducati", "1000", "bare_number"), ("MV Agusta", "20", "bare_number"),
        ("Aprilia", "1077cc", "bare_number"), ("Ducati", "06", "bare_number"),
        ("Ducati", "Gilera", "other_marque"), ("KTM", "Husqvarna", "other_marque"),
        ("Triumph", "Moto Morini", "other_marque"), ("Ducati", "Guzzi V85", "other_marque"),
        ("Ducati", "MV", "other_marque"), ("MV Agusta", "MV", "marque_name"),
        ("Harley-Davidson", "2020 service manual", "prose"),
        ("Aprilia", "approximately 2016 to 2020", "prose"),
        ("Triumph", "positive earth through 1978", "prose"),
        ("KTM", "S 1000 RR by type code", "prose"),
        # Ducati's engine families: an engine is not a machine (F135 group B).
        ("Ducati", "Testastretta", "engine_family"), ("Ducati", "Desmoquattro", "engine_family"),
        ("Ducati", "Superquadro", "engine_family"), ("Ducati", "Desmodue", "engine_family"),
        ("Ducati", "Desmoquattro 16-valve", "engine_family"), ("Ducati", "Testastretta MY2010", "engine_family"),
        ("Ducati", "998 Testastretta", "engine_family"),
        # Another make's machine, attached by one shared row (#912, #886).
        ("Ducati", "S 1000 XR", "other_make_model"), ("Aprilia", "S 1000 XR", "other_make_model"),
        ("Moto Guzzi", "S 1000 XR", "other_make_model"), ("Triumph", "S 1000 XR", "other_make_model"),
        ("KTM", "S 1000 XR", "other_make_model"), ("KTM", "Testastretta MY2010", "other_make_model"),
        ("BMW", "Testastretta MY2010", "other_make_model"), ("MV Agusta", "Testastretta MY2010", "other_make_model"),
        # Multi-make rows #4593/#4596 ('Kymco, SYM') and #4603 ('Yamaha, Kymco,
        # SYM, Genuine') pair every model with every make (F142).
        ("Kymco", "Jet 14", "other_make_model"), ("Kymco", "Fiddle 4", "other_make_model"),
        ("Kymco", "Wolf CR300i", "other_make_model"), ("SYM", "X-Town 300", "other_make_model"),
        ("Kymco", "XC50", "other_make_model"), ("SYM", "XC50", "other_make_model"),
        ("Genuine", "XC50", "other_make_model"),
    ])
    def test_the_class(self, make, spelling, cls):
        from census import not_a_machine
        assert not_a_machine(make, spelling) == cls

    @pytest.mark.parametrize("make,spelling", [
        ("Moto Guzzi", "Guzzi V85"), ("Yamaha", "Bolt"), ("Kawasaki", "ZX-10R"),
        ("SYM", "SYMBA 110"), ("Ducati", "1260 S"), ("Triumph", "Speed Triple"),
        ("MV Agusta", "Brutale"), ("KTM", "LC8"), ("Honda", "MVX250F"),
        # Machines whose name IS a number (bug fix #1: db920bb's shape rule
        # classed every one of these bare_number and never searched them).
        ("Ducati", "916"), ("Ducati", "996"), ("Ducati", "998"), ("Ducati", "999"),
        ("Ducati", "1098"), ("Ducati", "1198"), ("Ducati", "1299"), ("Ducati", "848"),
        ("Ducati", "749"), ("Ducati", "959"), ("Ducati", "899"), ("Ducati", "748"),
        ("Ducati", "851"), ("Ducati", "888"), ("Vespa", "946"), ("Piaggio", "946"),
        ("MV Agusta", "675"), ("MV Agusta", "910"), ("MV Agusta", "982"), ("MV Agusta", "1078"),
        ("MV Agusta", "750"), ("MV Agusta", "998"),
        # The entries above are make-scoped: under its own make the BMW is a
        # machine, and Ducati's own machines stay machines.
        ("BMW", "S 1000 XR"), ("Ducati", "Panigale V4"), ("Ducati", "Multistrada 1200"),
        ("Ducati", "Monster S4R"),
        # The true make keeps its machine (operator, 2026-09-23).
        ("SYM", "Jet 14"), ("SYM", "Fiddle 4"), ("Kymco", "X-Town 300"), ("Yamaha", "XC50"),
        ("SYM", "Wolf CR300i"),
    ])
    def test_a_machine_name_is_not_classed(self, make, spelling):
        """Including a marque's own model under its own marque, and a
        spelling that merely starts with the letters of one (SYMBA)."""
        from census import not_a_machine
        assert not_a_machine(make, spelling) is None

    def test_the_census_reports_them_as_their_own_count(self, tmp_path):
        from census import classes
        db = _db(tmp_path, [(1, "Ducati", "1000"), (2, "Ducati", "Gilera"),
                            (3, "Ducati", "Panigale V4"), (4, "Ducati", "2020 service manual")])
        assert classes(db) == {"Ducati": {"bare_number": ["1000"], "other_marque": ["Gilera"],
                                          "machine": ["Panigale V4"], "prose": ["2020 service manual"]}}


WOLF_QUOTE = ("Squeeze the clutch lever fully, operate change pedal to the proper position, "
              "then release the clutch lever to make a gear change.")


def _wolf(name, make="SYM"):
    """A finding citing an acquired copy of the SYM Wolf 150 manual."""
    return {"make": make, "spelling": "Wolf 150", "aliases": [], "outcome": "found", "transmission": "manual",
            "quote": WOLF_QUOTE, "document": str(FIX / "library" / "acquired" / "SYM" / name), "page": 18,
            "evidence_kind": "owners_manual"}


class TestAcquiredProvenance:
    """E11 — the Wolf 150 case. SYM USA's own maintenance-guide page links
    the Wolf 150 owner's manual on Dropbox (the library's `sym_mg.html`;
    the Dropbox PDF is byte-identical to `v2/sympdf/Wolf150_Owner_Manual.pdf`).
    Dropbox is not a SYM host, so the file counts only through its referrer:
    a page on a SYM host, itself in the library, unchanged, linking to it."""

    LIB = FIX / "library"

    def test_the_wolf_150_manual_counts_through_sym_usas_page(self):
        assert check([_wolf("wolf150_owner_manual.txt")], FIX, library=self.LIB) == []

    @pytest.mark.parametrize("name,why", [
        ("wolf150_noreferrer.txt", "no referrer on one"),
        ("wolf150_forumref.txt", "is not on a SYM host"),
        ("wolf150_unlinked.txt", "does not link to"),
        ("wolf150_staleref.txt", "has changed since it was recorded"),
        ("wolf150_tampered.txt", "no longer hashes"),
        ("wolf150_nosidecar.txt", "no readable"),
    ])
    def test_each_broken_provenance_is_rejected(self, name, why):
        fails = check([_wolf(name)], FIX, library=self.LIB)
        assert any(f.startswith("E11") and why in f for f in fails), fails

    def test_the_referrer_must_be_the_findings_makes(self):
        """SYM's page does not vouch for a Kymco finding."""
        fails = check([_wolf("wolf150_owner_manual.txt", make="Kymco")], FIX, library=self.LIB)
        assert any(f.startswith("E11") for f in fails), fails

    def test_a_document_on_the_makers_own_host_needs_no_referrer(self):
        f = {"make": "Genuine", "spelling": "Buddy 125", "aliases": [], "outcome": "found", "transmission": "cvt",
             "quote": "Transmission: automatic, V-belt (CVT)",
             "document": str(self.LIB / "acquired" / "Genuine" / "buddy125_owners_manual.txt"), "page": 1,
             "evidence_kind": "owners_manual"}
        assert check([f], FIX, library=self.LIB) == []

    @pytest.mark.parametrize("url,make,ok", [
        ("https://sym-usa.com/x", "SYM", True), ("https://www.sym-global.com/x", "SYM", True),
        ("https://sym-usa.com.evil.example/x", "SYM", False), ("https://notsym-usa.com/", "SYM", False),
        ("https://www.dropbox.com/s/x", "SYM", False),
    ])
    def test_maker_host_is_the_host_or_a_subdomain(self, url, make, ok):
        from library_index import maker_host
        assert maker_host(url, make) is ok


class TestTheReferrerLinkIsResolvedLikeABrowser:
    """A page saved with 'Save Page As' keeps relative links; E11 resolves
    each href/src against the page's own URL. The same page must not vouch
    for a file it does not link."""

    PAGE = (b'<html><a href="/content/dam/manuals/Panigale V4 OM.pdf">OM</a>'
            b'<a href="../spec/v4s.pdf">spec</a><img src="https://cdn.ducati.com/x.png"></html>')
    AT = "https://www.ducati.com/us/en/owners/owner-manuals"

    @pytest.mark.parametrize("url,ok", [
        ("https://www.ducati.com/content/dam/manuals/Panigale V4 OM.pdf", True),
        ("https://www.ducati.com/content/dam/manuals/Panigale%20V4%20OM.pdf", True),
        ("https://www.ducati.com/us/en/spec/v4s.pdf", True),
        ("https://www.ducati.com/content/dam/manuals/Monster OM.pdf", False),
        ("https://evil.example/content/dam/manuals/Panigale V4 OM.pdf", False),
    ])
    def test_relative_and_encoded_links(self, url, ok):
        from entry_check import links_to
        assert links_to(self.PAGE, self.AT, url) is ok


class TestNamesModel:
    """entry_check.names_model — the words of the model in a run, not
    followed by a variant word (VARIANT_TOKENS). Shapes from this phase."""

    @pytest.mark.parametrize("text,spelling,named", [
        ("KTM 1290 SUPER DUKE GT specifications", "1290 Super Duke", False),
        ("the 1290 Super Duke R is", "1290 Super Duke R", True),
        ("F 800 GS rider manual", "F800", False),
        ("Model WOLF CR 300i", "Wolf CR300i", True),
        ("Zero SR/S", "SR", False),
        ("Zero SR and SR/S", "SR", True),
        ("2025 Honda Grom Specifications", "Grom", True),
        ("Grom ABS (MSX125AS)", "Grom", True),
        ("K-PIPE 125 owner's manual", "K-Pipe", True),
        ("the Speed Triple 1200 RS", "Speed Triple 1200", False),
    ])
    def test_named(self, text, spelling, named):
        from entry_check import names_model
        assert names_model(text, spelling) is named
