"""Phase 255D — the closeout contract.

**What this asserts.** The ARTEFACTS a close-out is defined to produce, for a
phase. Not that closeout *ran* — that is unfalsifiable from inside a
repository, and a check that cannot fail is the defect this phase exists to
stop shipping.

**Why the fixtures are hand-written.** Decision 5, sharpened by 255C into
*independent reference*: a positive control must be satisfied by something
that does not reimplement the procedure. `fixtures/bad/` is a complete
miniature repository with one planted defect per assertion, written by hand
and committed. A fixture generated by the code under test would prove only
that the code agrees with itself — which is exactly how 255C shipped a guard
that could not fail.

**The check's own first bug is recorded here** because it is the reason this
file exists: the first cut of A4 used one `re.findall` with `re.S`, so a
non-greedy `.*?` ran across a newline and matched a later heading's number
from an earlier heading's line. It reported `#5` twice against a log whose
headings were a clean `#1..#7`. **The check was wrong, not the log** — the
same DOTALL-across-a-line-boundary defect that ate a guard in Phase 255B.
Caught by running the check against a real closed phase before trusting it.
"""
from __future__ import annotations

import json
import pathlib
import subprocess
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILL = ROOT / ".claude" / "skills" / "closeout"
sys.path.insert(0, str(SKILL))

from closeout_check import ASSERTION_IDS, check  # noqa: E402

BAD = SKILL / "fixtures" / "bad"
GOOD = SKILL / "fixtures" / "good"

#: The real phase this check is pinned against. 255C is the first phase
#: closed under it, and D6 requires the script to pass on a phase it was not
#: written for. Running only against fixtures would test the fixtures.
PINNED_REAL_PHASE = "255C"


class TestTheKnownBadFixtureFailsEveryAssertion:
    """A guard that cannot fail is not a guard."""

    @pytest.fixture(scope="class")
    def fails(self):
        return check(BAD, "ZZZ")

    @pytest.mark.parametrize("aid", ASSERTION_IDS)
    def test_this_assertion_fires(self, fails, aid):
        assert any(f.startswith(aid) for f in fails), (
            f"{aid} did not fire on the known-bad fixture, which plants one "
            f"defect per assertion. Either the planted defect was removed or "
            f"{aid} cannot fail. Failures seen: {fails}")

    def test_the_fixture_is_not_silently_empty(self, fails):
        assert len(fails) >= len(ASSERTION_IDS), (
            f"expected at least {len(ASSERTION_IDS)} failures, got {len(fails)}")


class TestA4RequiresTheCommitToResolve:
    """A Commit line must name a commit that exists.

    The first cut of A4 checked only that the words `**Commit.**` were
    present, so `This one.` passed — 255D bug fixes #5 and #6 shipped that
    way, and 255C #7 said "See the close-out commit". A check that passes on
    a non-answer cannot fail on the thing it exists for.
    """

    @pytest.fixture(scope="class")
    def a4(self):
        return [f for f in check(BAD, "ZZZ") if f.startswith("A4")]

    def test_a_non_hash_commit_line_fails(self, a4):
        assert any("name no" in f and "#1 'This one.'" in f for f in a4), a4

    def test_a_hash_that_is_not_a_commit_fails(self, a4):
        assert any("do not resolve" in f and "#4 aaaaaaa" in f for f in a4), a4

    def test_a_real_hash_resolves(self):
        from closeout_check import unresolved_commits
        assert unresolved_commits(ROOT, " `f279533`.") == []

    def test_a_sibling_repository_is_resolved_there(self):
        """`hash` (name) resolves in the sibling checkout `name`.

        Positive control: this repository named as its own sibling, so the
        test does not depend on any other checkout being present.
        """
        from closeout_check import unresolved_commits
        assert unresolved_commits(ROOT, f" `f279533` ({ROOT.name}).") == []

    def test_an_absent_sibling_is_reported_not_skipped(self):
        from closeout_check import unresolved_commits
        assert unresolved_commits(
            ROOT, " `f279533` (no-such-repo-255D).") == [
                "f279533 (no-such-repo-255D)"]


class TestA4HeadingsAreNotDatedAfterTheyWereRecorded:
    """A bug-fix heading may not carry a time later than the commit that
    wrote it. NOT "matches the fix commit": headings record when the entry
    was written, often in a close-out batch, and that rule failed 11 of 13
    honest entries across 255C and 255D."""

    LOG = ROOT / "docs" / "phases" / "completed" / "255D_phase_log.md"

    def test_the_known_bad_fixture_fires(self):
        a4 = [f for f in check(BAD, "ZZZ") if f.startswith("A4")]
        assert any("dated after" in f and "#1 heading 2099-01-01 10:00" in f
                   for f in a4), a4

    @pytest.mark.parametrize("heading", [
        # As they were first committed, in 7b578af (20:17), fc1f8fc (20:18)
        # and cf65268 (20:39). History is immutable, so this cannot drift.
        "### 2026-09-22 21:40 — Bug fix #5: B2 could not tell describing a number from citing one",
        "### 2026-09-22 21:55 — Bug fix #6: A7 could only ever be satisfied by the newest phase",
        "### 2026-09-22 22:40 — Bug fix #7: A4 passed on a non-answer",
    ])
    def test_the_real_mis_dated_headings_fire(self, heading):
        from closeout_check import dated_after_recording
        assert dated_after_recording(self.LOG, heading), heading

    def test_an_honest_batch_written_heading_passes(self):
        """255D #1 was written at 20:10 in a close-out batch committed at
        20:15, an hour after its fix. Late is honest; after is not."""
        from closeout_check import dated_after_recording
        assert dated_after_recording(
            self.LOG, "### 2026-09-22 20:10 — Bug fix #1: the closeout "
            "check's own A4 matched across a line boundary") is None

    def test_an_uncommitted_heading_is_judged_against_now(self):
        import datetime as dt
        from closeout_check import dated_after_recording
        head = "### 2026-09-22 12:00 — Bug fix #1: never committed ZZZ-255D"
        assert dated_after_recording(
            self.LOG, head, now=dt.datetime(2026, 9, 22, 11, 0))
        assert dated_after_recording(
            self.LOG, head, now=dt.datetime(2026, 9, 22, 13, 0)) is None


class TestTheKnownGoodFixturePasses:
    def test_no_assertion_fires(self):
        fails = check(GOOD, "ZZZ")
        assert fails == [], (
            "the corrected fixture must pass; a check that fails on correct "
            f"input is as useless as one that passes on bad: {fails}")


class TestA7TakesTheNewestRowByDate:
    """F148: A7 took the first bold history row as the newest phase. The
    table is not in date order and its first row is 244M, so the
    version-header half of A7 could fire for no other phase."""

    A7_BAD = SKILL / "fixtures" / "a7_newest_bad"
    A7_GOOD = SKILL / "fixtures" / "a7_newest_good"

    def test_a_stale_header_on_a_later_row_fires(self):
        fails = check(self.A7_BAD, "ZZZ")
        assert fails and all(f.startswith("A7") for f in fails), fails
        assert "does not name the newest phase ZZZ" in fails[0], fails

    def test_a_bumped_header_on_a_later_row_passes(self):
        assert check(self.A7_GOOD, "ZZZ") == []

    def test_the_first_row_is_not_held_to_the_header(self):
        """244M leads the fixture table but is not the newest, so a header
        naming ZZZ is no A7 failure for it (master's A7 reported one)."""
        fails = check(self.A7_GOOD, "244M")
        assert not any(f.startswith("A7") for f in fails), fails

    @pytest.mark.parametrize("order", [1, -1])
    def test_a_same_day_tie_goes_to_the_row_committed_later(self, order):
        """257 and 257B both closed 2026-09-24; 257B's row was committed
        in f3ef2fb (13:17), 257's in b8382b5 (00:07). History is
        immutable, so this cannot drift. Either table order gives 257B."""
        from closeout_check import newest_phase
        hist = ROOT / "implementation.md"
        rows = [ln for ln in hist.read_text(encoding="utf-8").splitlines()
                if ln.startswith(("| **257** |", "| **257B** |"))]
        assert len(rows) == 2, rows
        assert newest_phase(hist, rows[::order]) == "257B"


class TestAgainstTheRealRepository:
    def test_a_closed_phase_passes(self):
        """D6: run it against a phase it was not written for."""
        fails = check(ROOT, PINNED_REAL_PHASE)
        assert fails == [], (
            f"phase {PINNED_REAL_PHASE} is closed and must satisfy the "
            f"closeout contract: {fails}")

    def test_an_unknown_phase_does_not_pass_vacuously(self):
        """A phase with no documents at all must fail, not quietly succeed."""
        fails = check(ROOT, "999Q")
        assert fails, "a nonexistent phase passed the closeout check"


class TestThePushGuardNeverBlocksANonPushCommand:
    """v1.1-3. The lockout is the failure mode of this whole design.

    A guard on `Bash` that is wrong about WHICH commands it guards takes away
    the tool needed to remove it. This happened in D1: a guard meant for
    `git push` blocked a `cat`, because `PreToolUse` ignores the hook's `if`
    field in this build. Recovery was via the Write tool, which does not pass
    through a `Bash` matcher.
    """

    GUARD = SKILL / "pre_push_guard.sh"

    def _run(self, command: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            [str(self.GUARD)], input=json.dumps({
                "hook_event_name": "PreToolUse", "tool_name": "Bash",
                "tool_input": {"command": command}}),
            capture_output=True, text=True, timeout=120)

    @pytest.mark.parametrize("command", [
        "ls -la",
        "git status",
        "git log --oneline -3",
        'echo "git push"',                       # the words, inside a quote
        'grep -rn "git push" docs/',             # the words, as a search term
        "cat > /tmp/x <<'EOF'",
        "git pushx --not-a-real-subcommand",
    ])
    def test_a_non_push_command_is_let_through(self, command):
        r = self._run(command)
        assert r.returncode == 0, (
            f"the guard blocked a non-push command, which is the lockout "
            f"bug: {command!r} -> exit {r.returncode}\n{r.stderr}")

    def test_malformed_input_is_let_through(self):
        r = subprocess.run([str(self.GUARD)], input="not json",
                           capture_output=True, text=True, timeout=120)
        assert r.returncode == 0, (
            "the guard must stay out of the way when it cannot read its "
            "input; it must never be able to fail closed")

    @pytest.mark.parametrize("command", [
        "git push origin phase-255D-procedures-as-folders",
        "git push -u origin some-feature-branch",
    ])
    def test_a_phase_branch_push_is_let_through(self, command):
        """Close-out is what must happen before work reaches `master`.

        A phase branch is pushed many times while the phase is still open;
        that is normal, not a skipped close-out. A guard that blocked every
        push would block every work-in-progress push for the whole phase,
        and the only way to work would be to turn the guard off — which is
        worse than not having one.
        """
        r = self._run(command)
        assert r.returncode == 0, (
            f"the guard blocked a phase-branch push: {command!r}\n{r.stderr}")

    def test_master_is_recognised_as_guarded(self):
        from _pre_push_guard import targets_master
        assert targets_master("git push origin master", ROOT)
        assert targets_master("git push origin HEAD:master", ROOT)
        assert not targets_master("git push origin my-branch", ROOT)

    def test_a_real_push_is_recognised(self):
        """The other direction: the guard must actually engage on a push.

        It exits 0 here only if the repository's current phase is closed, so
        this asserts recognition rather than blocking — `is_git_push` is
        unit-tested for the classification itself.
        """
        from _pre_push_guard import is_git_push
        assert is_git_push("git push origin master")
        assert is_git_push("cd /x && git push -u origin branch")
        assert not is_git_push('echo "git push"')


class TestCheck2SeesCodeOutsideSrcAndTests:
    """F137. verify_phase.sh check 2 was `git diff -- src/ tests/`.

    Phase 255D fixes #5 and #6 changed two skill scripts after the closing
    regression, and check 2 reported "docs only". `.claude/` is code; the
    two-directory scope was an exclusion no one had written down as one.
    """

    FIX = SKILL / "fixtures" / "check2"

    @staticmethod
    def _paths(name):
        return (TestCheck2SeesCodeOutsideSrcAndTests.FIX / name).read_text(
            encoding="utf-8").splitlines()

    def test_a_skill_script_change_is_reported(self):
        from code_after_regression import code_paths
        assert code_paths(self._paths("bad_paths.txt")) == [
            ".claude/skills/closeout/closeout_check.py"]

    def test_a_docs_only_change_is_not(self):
        from code_after_regression import code_paths
        assert code_paths(self._paths("good_paths.txt")) == []

    def test_the_real_255D_miss_is_reported(self):
        """Positive control from history, not from a fixture.

        b0ae748 is 255D's closing regression; 3dfc78a is the merge of fix
        #6. Between them the old check 2 saw only a floor-test bump. Both
        commits are immutable, so this case cannot drift.
        """
        from code_after_regression import changed_since
        hits = changed_since(ROOT, "b0ae748", "3dfc78a")
        assert ".claude/skills/closeout/closeout_check.py" in hits, hits
        assert ".claude/skills/finding/finding_check.py" in hits, hits

    def test_every_tracked_script_is_code(self):
        """The exclusion needs a control too: nothing executable may fall
        through to "documentation"."""
        from code_after_regression import is_code
        tracked = subprocess.run(
            ["git", "-C", str(ROOT), "ls-files"], capture_output=True,
            text=True, check=True).stdout.splitlines()
        suffixes = (".py", ".sh", ".js", ".cjs", ".mjs", ".ts", ".toml",
                    ".yaml", ".yml", ".cfg", ".ini", ".sql")
        scripts = [p for p in tracked
                   if p.endswith(suffixes) and not p.startswith("docs/")]
        assert scripts, "the census found no scripts; the control is broken"
        missed = [p for p in scripts if not is_code(p)]
        assert missed == [], missed
