"""Phase 380: write migration 085's deploy scope from the seed.

Run from the repository root: `.venv/bin/python docs/phases/in_progress/380_scope.py`.
Committed in the phase folder because its output, `380_deploy_scope.json`,
is what the dry run and the live apply are held to (K24).

Every `known_issues` row may change in one field, `row_key`, and only to its
seed entry's frozen key (`"to"`). Each is found by its prose identity, which
is unique before 085 (the index 085 replaces), so each `where` matches
exactly one row. The scope is written from the SEED, not from live, so the
dry run checks one source against the other: a live row whose prose no seed
entry has fails `resolve` (no row matched), and a key written wrong fails
the `"to"` check.

The model junction may lose rows and gain none: Step 0 estimated 104, and
the build measured 109 on a live copy. The count is filled in from that
measurement, and the dry run must match it exactly.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
SEED = ROOT / "src" / "motodiag" / "knowledge" / "seed" / "knowledge"
OUT = pathlib.Path(__file__).resolve().parent / "380_deploy_scope.json"
JUNCTION_REMOVED = 109  # measured on a live copy at a119c28 (380_phase_log.md, D1)


def main() -> int:
    changed = []
    for path in sorted(SEED.glob("known_issues_*.json")):
        for entry in json.loads(path.read_text(encoding="utf-8")):
            changed.append({
                "where": "title = ? and make is ? and model is ?",
                "params": [entry["title"], entry.get("make"), entry.get("model")],
                "fields": ["row_key"],
                "to": {"row_key": entry["key"]},
            })
    scope = {
        "_comment": (
            "Phase 380, migration 085 (F129, F142). Every known_issues row gains its "
            "frozen row_key, and only that field changes, to the seed's key. The "
            "model junction loses the pairs that filed a multi-make row's model "
            "under a make not its own (measured: 109) and gains none. The prose "
            "identity index is replaced by idx_known_issues_row_key, and the "
            "known_issues table's SQL is rewritten by its new column. Generated by "
            "380_scope.py from the seed. Every table not named here must not "
            "change at all."),
        "tables": {
            "schema_version": {"added": 1},
            "known_issues": {"changed": changed},
            "known_issue_models": {"removed": JUNCTION_REMOVED},
        },
        "schema": {
            "added": ["index idx_known_issues_row_key"],
            "removed": ["index idx_known_issues_identity"],
            "changed": ["table known_issues"],
        },
    }
    OUT.write_text(json.dumps(scope, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name}: {len(changed)} known_issues rows, "
          f"{JUNCTION_REMOVED} junction rows removed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
