"""Phase 381: generate migration 086's known-issue data from the seed, by key.

    .venv/bin/python docs/phases/in_progress/381_gen086.py LIVE_COPY [--write]

Builds a fresh seed database the way deploy.py's parity check does (schema,
then every known_issues_*.json), and compares it with LIVE_COPY (a backup-API
copy of live, never live itself) by `row_key`, over the content columns:

* a key in both whose field differs  -> (key, field, live value, seed value);
* a key in live and in no seed entry -> a retired row, held in full with its
  junction pairs, so the rollback can put it back;
* a key in the seed and not in live  -> refused: 086 adds no row.

Prints the counts and, with --write, writes src/motodiag/core/migration_086_rows.py.
Committed in the phase folder (K24), as 380_add_keys.py was.
"""
from __future__ import annotations

import pathlib
import pprint
import sqlite3
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "src"))

OUT = ROOT / "src" / "motodiag" / "core" / "migration_086_rows.py"
FIELDS = ("title", "description", "make", "model", "year_start", "year_end",
          "severity", "symptoms", "dtc_codes", "causes", "fix_procedure",
          "parts_needed", "estimated_hours", "source", "applicability")


def fresh_seed(path: pathlib.Path) -> None:
    from motodiag.core.database import init_db
    from motodiag.knowledge.loader import load_known_issues_file

    init_db(str(path))
    seed = ROOT / "src" / "motodiag" / "knowledge" / "seed" / "knowledge"
    for f in sorted(seed.glob("known_issues_*.json")):
        load_known_issues_file(f, str(path))


def rows(db: pathlib.Path) -> dict[str, dict]:
    c = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
    c.row_factory = sqlite3.Row
    out = {r["row_key"]: dict(r) for r in c.execute("select * from known_issues")}
    c.close()
    return out


def junction(db: pathlib.Path, issue_id: int) -> tuple:
    c = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
    pairs = tuple(("known_issue_makes", issue_id, m, None) for (m,) in c.execute(
        "select make from known_issue_makes where issue_id = ? order by make", (issue_id,)))
    pairs += tuple(("known_issue_models", issue_id, m, mo) for m, mo in c.execute(
        "select make, model from known_issue_models where issue_id = ? order by make, model",
        (issue_id,)))
    c.close()
    return pairs


def main() -> int:
    live_db = pathlib.Path(sys.argv[1])
    with tempfile.TemporaryDirectory() as tmp:
        fresh = pathlib.Path(tmp) / "fresh.db"
        fresh_seed(fresh)
        seed = rows(fresh)
    live = rows(live_db)
    added = sorted(set(seed) - set(live))
    if added:
        print("refused: seed keys with no live row (086 adds none):", added)
        return 1
    changed = [(k, f, live[k][f], seed[k][f])
               for k in sorted(set(live) & set(seed)) for f in FIELDS
               if live[k][f] != seed[k][f]]
    retired = [{**{c: live[k][c] for c in ("id", "row_key", *FIELDS, "created_by_user_id")}}
               for k in sorted(set(live) - set(seed))]
    pairs = [p for r in retired for p in junction(live_db, r["id"])]
    keys = sorted({c[0] for c in changed})
    print(f"changed: {len(changed)} fields in {len(keys)} rows; retired: {len(retired)} rows, "
          f"{len(pairs)} junction pairs")
    for k, f, _, _ in changed:
        print("  ", k, f)
    for r in retired:
        print("   retired", r["id"], r["row_key"])
    if "--write" in sys.argv:
        OUT.write_text(
            '"""Migration 086\'s known-issue rows: live text -> seed text, by key.\n\n'
            "GENERATED by Phase 381 (docs/phases/in_progress/381_gen086.py), not\n"
            "written by hand. For every known_issues row whose content on a copy of\n"
            "the live database differs from a fresh seed build, it holds each\n"
            "differing field's live value (old) and the seed's (new), by the row's\n"
            "frozen key (F129). A live row no seed entry holds is retired, kept here\n"
            "in full with its junction pairs so the rollback can restore it.\n\n"
            f"{len(keys)} rows, {len(changed)} fields; {len(retired)} retired.\n"
            '"""\n\n'
            "#: (row_key, field, old, new)\n"
            f"CHANGED_ROWS_086 = {pprint.pformat(tuple(changed), width=100)}\n\n"
            "#: every column of each retired row, as live held it\n"
            f"RETIRED_ROWS_086 = {pprint.pformat(tuple(retired), width=100)}\n\n"
            "#: (table, issue_id, make, model or None) of each retired row\n"
            f"RETIRED_PAIRS_086 = {pprint.pformat(tuple(pairs), width=100)}\n",
            encoding="utf-8")
        print("wrote", OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
