"""Comparative audio analysis for before-vs-after diagnostics.

Phase 103: Compares a baseline audio recording against a current recording
to detect changes in engine sound — frequency shifts, new peaks, disappeared
peaks, amplitude changes. Produces an improvement score (-1.0 to 1.0) and
detailed difference report.

Designed for the mechanic workflow: record audio before repair, perform repair,
record audio after, compare to verify fix effectiveness.

Uses SpectrogramData for frequency analysis (defined locally since Phase 97's
SpectrogramAnalyzer has not been built yet — will be replaced with a proper
import when Phase 97 is complete).
"""

from __future__ import annotations

import math
from typing import Optional

from pydantic import BaseModel, Field

from motodiag.media.audio_capture import AudioSample


# --- Local Spectrogram Support ---
# Phase 97 (SpectrogramAnalyzer) does not exist yet. We define minimal
# spectrogram structures here so Phase 103 can operate independently.
# When Phase 97 is built, these can be replaced with imports.


class FrequencyPeak(BaseModel):
    """A detected peak in the frequency spectrum."""
    frequency_hz: float = Field(..., description="Center frequency of the peak in Hz")
    amplitude: float = Field(..., ge=0.0, description="Peak amplitude (arbitrary units)")
    bandwidth_hz: float = Field(default=10.0, ge=0.0, description="Width of the peak at -3dB")

    @property
    def is_low_frequency(self) -> bool:
        """Below 200 Hz — engine fundamental, exhaust."""
        return self.frequency_hz < 200.0

    @property
    def is_mid_frequency(self) -> bool:
        """200-2000 Hz — harmonics, valve train, chain."""
        return 200.0 <= self.frequency_hz < 2000.0

    @property
    def is_high_frequency(self) -> bool:
        """Above 2000 Hz — bearing whine, hiss, squeal."""
        return self.frequency_hz >= 2000.0


class SpectrogramData(BaseModel):
    """Simplified spectrogram representation for frequency analysis.

    In production, this would be generated by Phase 97's SpectrogramAnalyzer
    from actual audio data. Here it can be populated manually or via
    the analyze_frequencies() helper.
    """
    peaks: list[FrequencyPeak] = Field(
        default_factory=list,
        description="Detected frequency peaks",
    )
    dominant_frequency_hz: float = Field(
        default=0.0,
        description="Strongest frequency component",
    )
    total_energy: float = Field(
        default=0.0,
        ge=0.0,
        description="Total spectral energy (sum of peak amplitudes)",
    )
    noise_floor: float = Field(
        default=0.0,
        ge=0.0,
        description="Estimated background noise level",
    )
    sample_rate: int = Field(default=44100, description="Sample rate of the analyzed audio")

    @property
    def peak_count(self) -> int:
        return len(self.peaks)

    @property
    def snr(self) -> float:
        """Signal-to-noise ratio (dominant peak amplitude / noise floor)."""
        if self.noise_floor <= 0:
            return float("inf") if self.dominant_frequency_hz > 0 else 0.0
        dominant_amp = max((p.amplitude for p in self.peaks), default=0.0)
        return dominant_amp / self.noise_floor


def analyze_frequencies(sample: AudioSample, num_peaks: int = 10) -> SpectrogramData:
    """Simple frequency analysis via DFT on an AudioSample.

    This is a basic implementation using a naive DFT (not FFT) on a limited
    number of frequency bins. Adequate for comparative analysis; not meant
    for production spectrogram display.

    Args:
        sample: AudioSample to analyze.
        num_peaks: Maximum number of peaks to return.

    Returns:
        SpectrogramData with detected peaks and energy metrics.
    """
    if not sample.samples or len(sample.samples) < 2:
        return SpectrogramData(sample_rate=sample.sample_rate)

    n = len(sample.samples)
    sr = sample.sample_rate
    max_freq = sr // 2  # Nyquist

    # Compute magnitude at selected frequency bins
    # Use logarithmic spacing for motorcycle-relevant range (20 Hz - 10 kHz)
    num_bins = min(256, n // 2)
    if num_bins < 2:
        return SpectrogramData(sample_rate=sr)

    freq_bins: list[float] = []
    magnitudes: list[float] = []

    for i in range(num_bins):
        # Logarithmic frequency spacing from 20 Hz to min(10000, Nyquist)
        f = 20.0 * math.exp(math.log(min(10000, max_freq) / 20.0) * i / (num_bins - 1))
        if f > max_freq:
            break

        # DFT at this frequency
        real_part = 0.0
        imag_part = 0.0
        for j, s in enumerate(sample.samples):
            angle = 2.0 * math.pi * f * j / sr
            real_part += s * math.cos(angle)
            imag_part -= s * math.sin(angle)

        magnitude = math.sqrt(real_part ** 2 + imag_part ** 2) / n
        freq_bins.append(f)
        magnitudes.append(magnitude)

    if not magnitudes:
        return SpectrogramData(sample_rate=sr)

    # Find peaks (local maxima)
    peaks: list[FrequencyPeak] = []
    for i in range(1, len(magnitudes) - 1):
        if magnitudes[i] > magnitudes[i - 1] and magnitudes[i] > magnitudes[i + 1]:
            peaks.append(FrequencyPeak(
                frequency_hz=round(freq_bins[i], 1),
                amplitude=round(magnitudes[i], 6),
                bandwidth_hz=round(
                    freq_bins[min(i + 1, len(freq_bins) - 1)] - freq_bins[max(i - 1, 0)], 1
                ),
            ))

    # Sort by amplitude (strongest first) and take top N
    peaks.sort(key=lambda p: p.amplitude, reverse=True)
    peaks = peaks[:num_peaks]

    # Compute metrics
    dominant_freq = peaks[0].frequency_hz if peaks else 0.0
    total_energy = sum(m for m in magnitudes)
    noise_floor = sorted(magnitudes)[len(magnitudes) // 4] if magnitudes else 0.0  # 25th percentile

    return SpectrogramData(
        peaks=peaks,
        dominant_frequency_hz=round(dominant_freq, 1),
        total_energy=round(total_energy, 6),
        noise_floor=round(noise_floor, 6),
        sample_rate=sr,
    )


# --- Comparison Models ---


class FrequencyChange(BaseModel):
    """A detected change in a frequency component between baseline and current."""
    frequency_hz: float = Field(..., description="Frequency of the change")
    baseline_amplitude: float = Field(default=0.0, description="Amplitude in baseline")
    current_amplitude: float = Field(default=0.0, description="Amplitude in current")
    change_type: str = Field(
        ...,
        description="Type: 'new_peak', 'disappeared_peak', 'amplitude_increase', "
                    "'amplitude_decrease', 'frequency_shift'",
    )
    change_magnitude: float = Field(
        default=0.0,
        description="Magnitude of change (ratio or absolute depending on type)",
    )
    diagnostic_hint: str = Field(
        default="",
        description="What this change might indicate diagnostically",
    )


class ComparisonResult(BaseModel):
    """Result of comparing baseline vs current audio recordings."""
    baseline_summary: str = Field(
        default="",
        description="Summary of baseline audio characteristics",
    )
    current_summary: str = Field(
        default="",
        description="Summary of current audio characteristics",
    )
    differences: list[str] = Field(
        default_factory=list,
        description="Human-readable description of each detected difference",
    )
    frequency_changes: list[FrequencyChange] = Field(
        default_factory=list,
        description="Detailed frequency-level changes",
    )
    improvement_score: float = Field(
        default=0.0,
        ge=-1.0,
        le=1.0,
        description="Overall improvement: -1.0 = worse, 0.0 = same, 1.0 = fully resolved",
    )
    new_anomalies: list[str] = Field(
        default_factory=list,
        description="New issues that appeared after the repair",
    )
    resolved_anomalies: list[str] = Field(
        default_factory=list,
        description="Issues present in baseline that are gone in current",
    )
    energy_change_percent: float = Field(
        default=0.0,
        description="Percent change in total spectral energy (+ = louder, - = quieter)",
    )
    dominant_frequency_shift_hz: float = Field(
        default=0.0,
        description="Shift in dominant frequency (Hz)",
    )

    @property
    def improved(self) -> bool:
        """Whether the overall assessment is positive (score > 0)."""
        return self.improvement_score > 0.0

    @property
    def worsened(self) -> bool:
        """Whether the overall assessment is negative (score < 0)."""
        return self.improvement_score < 0.0

    @property
    def unchanged(self) -> bool:
        """Whether the assessment shows no significant change."""
        return abs(self.improvement_score) < 0.05


# --- Diagnostic Hint Mapping ---

_FREQUENCY_HINTS: dict[str, str] = {
    "new_low": "New low-frequency peak may indicate exhaust leak or loose component",
    "new_mid": "New mid-frequency peak may indicate valve train issue or chain noise",
    "new_high": "New high-frequency peak may indicate bearing wear or belt squeal",
    "gone_low": "Disappeared low-frequency component — exhaust or mounting issue may be resolved",
    "gone_mid": "Disappeared mid-frequency noise — valve train or chain issue may be resolved",
    "gone_high": "Disappeared high-frequency noise — bearing or belt issue may be resolved",
    "louder_low": "Increased low-frequency energy — possible exhaust change or knock",
    "louder_mid": "Increased mid-frequency energy — possible valve or timing change",
    "louder_high": "Increased high-frequency energy — possible new wear noise",
    "quieter_low": "Decreased low-frequency energy — exhaust may be more sealed",
    "quieter_mid": "Decreased mid-frequency energy — less mechanical noise",
    "quieter_high": "Decreased high-frequency energy — bearing/belt noise reduced",
}


def _get_frequency_hint(change_type: str, frequency_hz: float) -> str:
    """Look up a diagnostic hint based on change type and frequency range."""
    if frequency_hz < 200:
        band = "low"
    elif frequency_hz < 2000:
        band = "mid"
    else:
        band = "high"

    if change_type == "new_peak":
        key = f"new_{band}"
    elif change_type == "disappeared_peak":
        key = f"gone_{band}"
    elif change_type == "amplitude_increase":
        key = f"louder_{band}"
    elif change_type == "amplitude_decrease":
        key = f"quieter_{band}"
    else:
        key = f"new_{band}"  # Fallback

    return _FREQUENCY_HINTS.get(key, "Frequency change detected — correlate with other symptoms")


class ComparativeAnalyzer:
    """Compares baseline vs current audio for before/after repair analysis.

    Workflow:
    1. Record baseline audio (before repair)
    2. Perform repair
    3. Record current audio (after repair)
    4. compare() → get improvement score and detailed differences

    Usage:
        analyzer = ComparativeAnalyzer()
        result = analyzer.compare(baseline_sample, current_sample)
        print(f"Improvement: {result.improvement_score:.2f}")
    """

    def __init__(
        self,
        frequency_tolerance_hz: float = 15.0,
        amplitude_change_threshold: float = 0.3,
        num_peaks: int = 10,
    ):
        """Initialize the comparative analyzer.

        Args:
            frequency_tolerance_hz: Two peaks within this range are considered
                the same frequency (accounts for slight RPM differences).
            amplitude_change_threshold: Minimum fractional amplitude change
                to count as significant (0.3 = 30% change).
            num_peaks: Number of frequency peaks to analyze per recording.
        """
        self.frequency_tolerance_hz = frequency_tolerance_hz
        self.amplitude_change_threshold = amplitude_change_threshold
        self.num_peaks = num_peaks

    def compare(
        self,
        baseline: AudioSample,
        current: AudioSample,
        baseline_spectrum: Optional[SpectrogramData] = None,
        current_spectrum: Optional[SpectrogramData] = None,
    ) -> ComparisonResult:
        """Compare baseline and current audio recordings.

        If spectrogram data is not provided, it is computed from the audio
        samples using the local analyze_frequencies() function.

        Args:
            baseline: Baseline (pre-repair) audio sample.
            current: Current (post-repair) audio sample.
            baseline_spectrum: Pre-computed spectrum for baseline (optional).
            current_spectrum: Pre-computed spectrum for current (optional).

        Returns:
            ComparisonResult with differences, improvement score, and anomalies.
        """
        # Analyze spectra if not provided
        if baseline_spectrum is None:
            baseline_spectrum = analyze_frequencies(baseline, self.num_peaks)
        if current_spectrum is None:
            current_spectrum = analyze_frequencies(current, self.num_peaks)

        # Identify frequency-level changes
        frequency_changes = self.identify_changes(baseline_spectrum, current_spectrum)

        # Categorize into resolved vs new anomalies
        new_anomalies = []
        resolved_anomalies = []
        differences = []

        for change in frequency_changes:
            if change.change_type == "new_peak":
                new_anomalies.append(
                    f"New {change.frequency_hz:.0f} Hz peak (amp={change.current_amplitude:.4f})"
                )
                differences.append(
                    f"New peak at {change.frequency_hz:.0f} Hz — {change.diagnostic_hint}"
                )
            elif change.change_type == "disappeared_peak":
                resolved_anomalies.append(
                    f"Resolved {change.frequency_hz:.0f} Hz peak (was amp={change.baseline_amplitude:.4f})"
                )
                differences.append(
                    f"Peak at {change.frequency_hz:.0f} Hz is gone — {change.diagnostic_hint}"
                )
            elif change.change_type in ("amplitude_increase", "amplitude_decrease"):
                direction = "increased" if change.change_type == "amplitude_increase" else "decreased"
                differences.append(
                    f"{change.frequency_hz:.0f} Hz amplitude {direction} by "
                    f"{abs(change.change_magnitude):.0%} — {change.diagnostic_hint}"
                )

        # Energy comparison
        energy_change_pct = 0.0
        if baseline_spectrum.total_energy > 0:
            energy_change_pct = (
                (current_spectrum.total_energy - baseline_spectrum.total_energy)
                / baseline_spectrum.total_energy
            ) * 100

        # Dominant frequency shift
        dom_shift = current_spectrum.dominant_frequency_hz - baseline_spectrum.dominant_frequency_hz

        # Score improvement
        improvement_score = self.score_improvement(
            frequency_changes=frequency_changes,
            energy_change_pct=energy_change_pct,
            baseline_spectrum=baseline_spectrum,
            current_spectrum=current_spectrum,
        )

        # Build summaries
        baseline_summary = self._summarize_spectrum(baseline_spectrum, "Baseline")
        current_summary = self._summarize_spectrum(current_spectrum, "Current")

        return ComparisonResult(
            baseline_summary=baseline_summary,
            current_summary=current_summary,
            differences=differences,
            frequency_changes=frequency_changes,
            improvement_score=round(improvement_score, 3),
            new_anomalies=new_anomalies,
            resolved_anomalies=resolved_anomalies,
            energy_change_percent=round(energy_change_pct, 1),
            dominant_frequency_shift_hz=round(dom_shift, 1),
        )

    def identify_changes(
        self,
        baseline: SpectrogramData,
        current: SpectrogramData,
    ) -> list[FrequencyChange]:
        """Detect frequency shifts, new peaks, and disappeared peaks.

        Matches peaks between baseline and current by frequency proximity
        (within tolerance_hz), then categorizes unmatched peaks as new or
        disappeared.

        Args:
            baseline: Baseline spectrogram data.
            current: Current spectrogram data.

        Returns:
            List of FrequencyChange objects describing each detected change.
        """
        changes: list[FrequencyChange] = []
        matched_baseline: set[int] = set()
        matched_current: set[int] = set()

        # Match peaks by frequency proximity
        for i, bp in enumerate(baseline.peaks):
            best_match: Optional[int] = None
            best_dist = float("inf")

            for j, cp in enumerate(current.peaks):
                if j in matched_current:
                    continue
                dist = abs(bp.frequency_hz - cp.frequency_hz)
                if dist < self.frequency_tolerance_hz and dist < best_dist:
                    best_match = j
                    best_dist = dist

            if best_match is not None:
                matched_baseline.add(i)
                matched_current.add(best_match)
                cp = current.peaks[best_match]

                # Check amplitude change
                if bp.amplitude > 0:
                    ratio = (cp.amplitude - bp.amplitude) / bp.amplitude
                    if abs(ratio) >= self.amplitude_change_threshold:
                        change_type = (
                            "amplitude_increase" if ratio > 0 else "amplitude_decrease"
                        )
                        changes.append(FrequencyChange(
                            frequency_hz=bp.frequency_hz,
                            baseline_amplitude=bp.amplitude,
                            current_amplitude=cp.amplitude,
                            change_type=change_type,
                            change_magnitude=ratio,
                            diagnostic_hint=_get_frequency_hint(change_type, bp.frequency_hz),
                        ))

        # Peaks in baseline but not current = disappeared
        for i, bp in enumerate(baseline.peaks):
            if i not in matched_baseline:
                changes.append(FrequencyChange(
                    frequency_hz=bp.frequency_hz,
                    baseline_amplitude=bp.amplitude,
                    current_amplitude=0.0,
                    change_type="disappeared_peak",
                    change_magnitude=-1.0,
                    diagnostic_hint=_get_frequency_hint("disappeared_peak", bp.frequency_hz),
                ))

        # Peaks in current but not baseline = new
        for j, cp in enumerate(current.peaks):
            if j not in matched_current:
                changes.append(FrequencyChange(
                    frequency_hz=cp.frequency_hz,
                    baseline_amplitude=0.0,
                    current_amplitude=cp.amplitude,
                    change_type="new_peak",
                    change_magnitude=1.0,
                    diagnostic_hint=_get_frequency_hint("new_peak", cp.frequency_hz),
                ))

        return changes

    def score_improvement(
        self,
        frequency_changes: list[FrequencyChange],
        energy_change_pct: float,
        baseline_spectrum: SpectrogramData,
        current_spectrum: SpectrogramData,
    ) -> float:
        """Calculate an overall improvement score from -1.0 to 1.0.

        Scoring factors:
        - Resolved peaks (positive): each resolved anomaly adds to the score
        - New peaks (negative): each new anomaly subtracts from the score
        - Amplitude decreases in anomaly frequencies (positive)
        - Amplitude increases in anomaly frequencies (negative)
        - Overall energy decrease (slightly positive — quieter = smoother)

        Returns:
            Float from -1.0 (much worse) to 1.0 (fully resolved).
        """
        if not frequency_changes:
            # No changes detected
            return 0.0

        score = 0.0
        max_possible = 0.0

        for change in frequency_changes:
            if change.change_type == "disappeared_peak":
                score += 0.3
                max_possible += 0.3
            elif change.change_type == "new_peak":
                score -= 0.3
                max_possible += 0.3
            elif change.change_type == "amplitude_decrease":
                score += 0.15 * min(abs(change.change_magnitude), 1.0)
                max_possible += 0.15
            elif change.change_type == "amplitude_increase":
                score -= 0.15 * min(abs(change.change_magnitude), 1.0)
                max_possible += 0.15

        # Energy factor: quieter engine is generally positive (less noise)
        if energy_change_pct < -10:
            score += 0.1
        elif energy_change_pct > 20:
            score -= 0.1
        max_possible += 0.1

        # Normalize to -1.0 to 1.0
        if max_possible == 0:
            return 0.0

        normalized = score / max_possible
        return max(-1.0, min(1.0, normalized))

    def _summarize_spectrum(self, spectrum: SpectrogramData, label: str) -> str:
        """Produce a human-readable summary of a spectrogram."""
        if not spectrum.peaks:
            return f"{label}: No significant frequency peaks detected."

        top_freqs = [f"{p.frequency_hz:.0f} Hz" for p in spectrum.peaks[:5]]
        return (
            f"{label}: {spectrum.peak_count} peaks detected. "
            f"Dominant: {spectrum.dominant_frequency_hz:.0f} Hz. "
            f"Top frequencies: {', '.join(top_freqs)}. "
            f"Total energy: {spectrum.total_energy:.4f}."
        )
