"""Phase 381: generate migration 086's deploy scope from its own data.

    .venv/bin/python docs/phases/in_progress/381_scope.py LIVE_COPY

Writes docs/phases/in_progress/381_deploy_scope.json. Every changed row is
named by its key (known_issues), its template slug and number (checklist
items) or its code and make (the DTC), with the fields that may change and
the exact text each must hold afterwards: the seed's for known issues, and
for the checklist and DTC edits the live text with the migration's
replacement applied. Committed in the phase folder (K24), as 380_scope.py was.
"""
from __future__ import annotations

import json
import pathlib
import sqlite3
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "src"))

from motodiag.core.migration_086_rows import CHANGED_ROWS_086, RETIRED_ROWS_086  # noqa: E402
from motodiag.core.migrations import _CHECKLIST_086, _DTC_086, _SYM_SPELLINGS_086  # noqa: E402

OUT = ROOT / "docs" / "phases" / "in_progress" / "381_deploy_scope.json"


def main() -> int:
    live = sqlite3.connect(f"file:{sys.argv[1]}?mode=ro", uri=True)
    by_key: dict[str, dict] = {}
    for key, field, _old, new in CHANGED_ROWS_086:
        entry = by_key.setdefault(key, {"where": "row_key = ?", "params": [key],
                                        "fields": [], "to": {}})
        entry["fields"].append(field)
        entry["to"][field] = new
    checklist = []
    for slug, seq, field, old, new in _CHECKLIST_086:
        held = live.execute(
            f"select c.{field} from checklist_items c join workflow_templates t"
            " on t.id = c.template_id where t.slug = ? and c.sequence_number = ?",
            (slug, seq)).fetchone()[0]
        assert held.count(old) == 1, (slug, seq)
        checklist.append({"where": "template_id = (select id from workflow_templates where"
                                   " slug = ?) and sequence_number = ?",
                          "params": [slug, seq], "fields": [field],
                          "to": {field: held.replace(old, new)}})
    dtc = []
    for code, make, field, old, new in _DTC_086:
        held = live.execute(f"select {field} from dtc_codes where code = ? and make = ?",
                            (code, make)).fetchone()[0]
        assert held.count(old) == 1, (code, make)
        dtc.append({"where": "code = ? and make = ?", "params": [code, make],
                    "fields": [field], "to": {field: held.replace(old, new)}})
    cvt_rows = sum(1 for k, f, _o, n in CHANGED_ROWS_086 if f == "model" and "SYM Jet Euro 50" in n)
    scope = {
        "_comment": (
            "Phase 381, migration 086 (schema 85 -> 86), the content batch on the row key. "
            f"{len(by_key)} known_issues rows change, each by its row_key, only in the fields "
            "named and only to the seed's text (F152, F153, F171, F158). F149's "
            f"{len(RETIRED_ROWS_086)} rows are removed with their make pairs. The model "
            f"junction gains the {len(_SYM_SPELLINGS_086)} SYM spellings on the "
            f"{cvt_rows} CVT rows that carry them (F153) and loses nothing. Two checklist "
            "items (F171, F164) and one DTC (F158) change in one field each. Generated by "
            "381_scope.py from the migration's own data. Every table not named here must not "
            "change at all."),
        "tables": {
            "schema_version": {"added": 1},
            "known_issues": {"removed": len(RETIRED_ROWS_086), "changed": list(by_key.values())},
            "known_issue_makes": {"removed": len(RETIRED_ROWS_086)},
            "known_issue_models": {"added": len(_SYM_SPELLINGS_086) * cvt_rows},
            "checklist_items": {"changed": checklist},
            "dtc_codes": {"changed": dtc},
        },
    }
    OUT.write_text(json.dumps(scope, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print("wrote", OUT.relative_to(ROOT), "-", len(by_key), "known issues,",
          len(checklist), "items,", len(dtc), "DTC")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
