"""Shop management — profile, customer intake, work orders, triage, invoicing.

Phase 160 opens this package with shop profile CRUD + intake visit
logging (the "arrived on lot" event). Subsequent Track G phases layer
work orders (161), structured issues (162), triage + scheduling
(163-168), invoicing (169), and analytics (171) on top of the
intake_visits row introduced here.
"""

from motodiag.shop.sourcing_models import (
    Availability,
    SourceTier,
    SourcingRecommendation,
    TierPreference,
    VendorSuggestion,
)
from motodiag.shop.parts_sourcing import (
    SOURCING_SYSTEM_PROMPT,
    VALID_TIER_PREFERENCES,
    BatchTimeoutError,
    InvalidTierPreferenceError,
    PartNotFoundError,
    SourcingParseError,
    get_recommendation,
    recommend_source,
    sourcing_budget,
)
from motodiag.shop.parts_needs import (
    PART_STATUSES,
    ConsolidatedPartNeed,
    InvalidPartNeedTransition,
    PartNotInCatalogError,
    Requisition,
    WorkOrderPartLine,
    WorkOrderPartNotFoundError,
    add_part_to_work_order,
    build_requisition,
    cancel_part_need,
    get_requisition,
    list_parts_for_shop_open_wos,
    list_parts_for_wo,
    list_requisitions,
    mark_part_installed,
    mark_part_ordered,
    mark_part_received,
    remove_part_from_work_order,
    update_part_cost_override,
    update_part_quantity,
)
from motodiag.shop.triage_queue import (
    ShopTriageError,
    ShopTriageWeights,
    TriageItem,
    build_triage_queue,
    clear_urgent,
    flag_urgent,
    load_triage_weights,
    reset_triage_weights,
    save_triage_weights,
    skip_work_order,
)
from motodiag.shop.priority_models import (
    PriorityScore,
    PriorityScoreResponse,
    PriorityScorerInput,
)
from motodiag.shop.priority_scorer import (
    CONFIDENCE_APPLY_THRESHOLD,
    DEFAULT_RESCORE_LIMIT,
    DEFAULT_SESSION_BUDGET_CENTS,
    PER_CALL_COST_CAP_CENTS,
    PRIORITY_SYSTEM_PROMPT,
    PriorityBudgetExhausted,
    PriorityCostCapExceeded,
    PriorityScorerError,
    get_latest_priority_score,
    priority_budget,
    rescore_all_open,
    score_work_order,
)
from motodiag.shop.ai_client import (
    MODEL_ALIASES,
    MODEL_PRICING,
    AIResponse,
    ShopAIClient,
    ShopAIClientError,
    TokenUsage,
    calculate_cost,
    extract_json_block,
    get_anthropic_client,
    resolve_model,
)
from motodiag.shop.shop_repo import (
    ShopNameExistsError,
    ShopNotFoundError,
    create_shop,
    deactivate_shop,
    delete_shop,
    get_shop,
    get_shop_by_name,
    list_shops,
    update_shop,
)
from motodiag.shop.intake_repo import (
    INTAKE_CLOSE_REASONS,
    INTAKE_STATUSES,
    IntakeAlreadyClosedError,
    IntakeNotFoundError,
    cancel_intake,
    close_intake,
    count_intakes,
    create_intake,
    get_intake,
    list_intakes,
    list_open_for_bike,
    reopen_intake,
    update_intake,
)
from motodiag.shop.work_order_repo import (
    TERMINAL_STATUSES as WORK_ORDER_TERMINAL_STATUSES,
    WORK_ORDER_STATUSES,
    InvalidWorkOrderTransition,
    WorkOrderFKError,
    WorkOrderNotFoundError,
    assign_mechanic,
    cancel_work_order,
    complete_work_order,
    count_work_orders,
    create_work_order,
    get_work_order,
    list_work_orders,
    open_work_order,
    pause_work,
    reopen_work_order,
    require_work_order,
    resume_work,
    start_work,
    unassign_mechanic,
    update_work_order,
)
from motodiag.shop.issue_repo import (
    ISSUE_CATEGORIES,
    ISSUE_SEVERITIES,
    ISSUE_STATUSES,
    SEVERITY_RANK,
    SYMPTOM_CATEGORY_TO_ISSUE_CATEGORY,
    TERMINAL_ISSUE_STATUSES,
    InvalidIssueTransition,
    IssueFKError,
    IssueNotFoundError,
    categorize_issue,
    count_issues,
    create_issue,
    get_issue,
    issue_stats,
    link_dtc,
    link_symptom,
    list_issues,
    mark_duplicate_issue,
    mark_wontfix_issue,
    reopen_issue,
    require_issue,
    resolve_issue,
    update_issue,
)


__all__ = [
    # parts_sourcing + sourcing_models (Phase 166)
    "Availability",
    "BatchTimeoutError",
    "InvalidTierPreferenceError",
    "PartNotFoundError",
    "SOURCING_SYSTEM_PROMPT",
    "SourceTier",
    "SourcingParseError",
    "SourcingRecommendation",
    "TierPreference",
    "VALID_TIER_PREFERENCES",
    "VendorSuggestion",
    "get_recommendation",
    "recommend_source",
    "sourcing_budget",
    # parts_needs (Phase 165)
    "PART_STATUSES",
    "ConsolidatedPartNeed",
    "InvalidPartNeedTransition",
    "PartNotInCatalogError",
    "Requisition",
    "WorkOrderPartLine",
    "WorkOrderPartNotFoundError",
    "add_part_to_work_order",
    "build_requisition",
    "cancel_part_need",
    "get_requisition",
    "list_parts_for_shop_open_wos",
    "list_parts_for_wo",
    "list_requisitions",
    "mark_part_installed",
    "mark_part_ordered",
    "mark_part_received",
    "remove_part_from_work_order",
    "update_part_cost_override",
    "update_part_quantity",
    # triage_queue (Phase 164)
    "ShopTriageError",
    "ShopTriageWeights",
    "TriageItem",
    "build_triage_queue",
    "clear_urgent",
    "flag_urgent",
    "load_triage_weights",
    "reset_triage_weights",
    "save_triage_weights",
    "skip_work_order",
    # priority_scorer + priority_models (Phase 163)
    "CONFIDENCE_APPLY_THRESHOLD",
    "DEFAULT_RESCORE_LIMIT",
    "DEFAULT_SESSION_BUDGET_CENTS",
    "PER_CALL_COST_CAP_CENTS",
    "PRIORITY_SYSTEM_PROMPT",
    "PriorityBudgetExhausted",
    "PriorityCostCapExceeded",
    "PriorityScore",
    "PriorityScoreResponse",
    "PriorityScorerError",
    "PriorityScorerInput",
    "get_latest_priority_score",
    "priority_budget",
    "rescore_all_open",
    "score_work_order",
    # ai_client (Phase 162.5)
    "MODEL_ALIASES",
    "MODEL_PRICING",
    "AIResponse",
    "ShopAIClient",
    "ShopAIClientError",
    "TokenUsage",
    "calculate_cost",
    "extract_json_block",
    "get_anthropic_client",
    "resolve_model",
    # shop_repo
    "ShopNameExistsError",
    "ShopNotFoundError",
    "create_shop",
    "deactivate_shop",
    "delete_shop",
    "get_shop",
    "get_shop_by_name",
    "list_shops",
    "update_shop",
    # intake_repo
    "INTAKE_CLOSE_REASONS",
    "INTAKE_STATUSES",
    "IntakeAlreadyClosedError",
    "IntakeNotFoundError",
    "cancel_intake",
    "close_intake",
    "count_intakes",
    "create_intake",
    "get_intake",
    "list_intakes",
    "list_open_for_bike",
    "reopen_intake",
    "update_intake",
    # work_order_repo
    "WORK_ORDER_STATUSES",
    "WORK_ORDER_TERMINAL_STATUSES",
    "InvalidWorkOrderTransition",
    "WorkOrderFKError",
    "WorkOrderNotFoundError",
    "assign_mechanic",
    "cancel_work_order",
    "complete_work_order",
    "count_work_orders",
    "create_work_order",
    "get_work_order",
    "list_work_orders",
    "open_work_order",
    "pause_work",
    "reopen_work_order",
    "require_work_order",
    "resume_work",
    "start_work",
    "unassign_mechanic",
    "update_work_order",
    # issue_repo
    "ISSUE_CATEGORIES",
    "ISSUE_SEVERITIES",
    "ISSUE_STATUSES",
    "SEVERITY_RANK",
    "SYMPTOM_CATEGORY_TO_ISSUE_CATEGORY",
    "TERMINAL_ISSUE_STATUSES",
    "InvalidIssueTransition",
    "IssueFKError",
    "IssueNotFoundError",
    "categorize_issue",
    "count_issues",
    "create_issue",
    "get_issue",
    "issue_stats",
    "link_dtc",
    "link_symptom",
    "list_issues",
    "mark_duplicate_issue",
    "mark_wontfix_issue",
    "reopen_issue",
    "require_issue",
    "resolve_issue",
    "update_issue",
]
